# Pre-commit hooks for Duel Log App
# See https://pre-commit.com for more information

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml

  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: ^backend/
        language_version: python3.12

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/
      - id: ruff-format
        files: ^backend/

  # Frontend formatting and linting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/
        types_or: [javascript, jsx, ts, tsx, vue, css, scss, json, yaml, markdown]
        additional_dependencies:
          - prettier@3.6.2

  # TypeScript type checking (optional, can be slow)
  # - repo: local
  #   hooks:
  #     - id: vue-tsc
  #       name: vue-tsc
  #       entry: bash -c 'cd frontend && npx vue-tsc --noEmit'
  #       language: system
  #       files: ^frontend/.*\.(ts|vue)$
  #       pass_filenames: false
