### Create User
POST http://localhost:8000/users/
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": "securepassword"
}

### Get User by ID
GET http://localhost:8000/users/1

### Update User
PUT http://localhost:8000/users/1
Content-Type: application/json

{
  "username": "updateduser",
  "email": "updated@example.com"
}

### Delete User
DELETE http://localhost:8000/users/1

### Create Deck
POST http://localhost:8000/decks/
Content-Type: application/json

{
  "user_id": 1,
  "name": "My First Deck"
}

### Get Decks for Current User
GET http://localhost:8000/decks/


### Get Deck by ID
GET http://localhost:8000/decks/1


### Update Deck
PUT http://localhost:8000/decks/1
Content-Type: application/json


{
  "name": "Updated Deck Name"
}

### Delete Deck
DELETE http://localhost:8000/decks/1
