name: 機能要望
description: 新しい機能やアイデアを提案する
title: "[機能要望] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        機能要望ありがとうございます！あなたのアイデアを教えてください。

  - type: dropdown
    id: feature-category
    attributes:
      label: 機能カテゴリ
      description: どの分野の機能要望ですか？
      options:
        - ログイン・認証
        - デッキ管理
        - 対戦記録の登録
        - 統計情報の表示
        - OBS配信オーバーレイ
        - プロフィール設定
        - CSVインポート/エクスポート
        - UI/UXの改善
        - 新機能
        - その他
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 解決したい課題
      description: 現在、どのような不便や課題がありますか？
      placeholder: |
        例：
        - 複数の対戦記録を一度に登録したいが、1件ずつ入力する必要があり手間がかかる
        - 統計情報をPDF形式でエクスポートできないため、報告書作成が面倒
        - スマートフォンでの操作がしづらい
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 提案する解決策
      description: どのような機能があれば解決できると思いますか？
      placeholder: |
        例：
        - CSVファイルから一括で対戦記録をインポートできる機能
        - 統計情報をPDF形式でエクスポートできるボタン
        - スマートフォン向けのUIデザイン改善
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: あなたにとってどれくらい重要ですか？
      options:
        - 高 - とても必要
        - 中 - あると便利
        - 低 - あったらいいな程度
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に考えられる解決方法はありますか？
      placeholder: 例：手動でPDF作成ツールを使う、など
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 補足情報
      description: スクリーンショットや参考資料があれば追加してください
      placeholder: |
        - 他のアプリの例
        - イメージ図
        - 参考URL
    validations:
      required: false

  - type: checkboxes
    id: user-type
    attributes:
      label: ユーザータイプ
      description: あなたはどのようなユーザーですか？（複数選択可）
      options:
        - label: 一般プレイヤー
        - label: 配信者
        - label: 大会主催者
        - label: その他
