"""Rename duel columns for clarity

Revision ID: 142a04659e9c
Revises: c9d8e7f6g5h4
Create Date: 2025-10-30 11:12:23.380462

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "142a04659e9c"
down_revision = "c9d8e7f6g5h4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("duels", "opponentDeck_id", new_column_name="opponent_deck_id")
    op.alter_column("duels", "result", new_column_name="is_win")
    op.alter_column("duels", "coin", new_column_name="won_coin_toss")
    op.alter_column("duels", "first_or_second", new_column_name="is_going_first")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("duels", "opponent_deck_id", new_column_name="opponentDeck_id")
    op.alter_column("duels", "is_win", new_column_name="result")
    op.alter_column("duels", "won_coin_toss", new_column_name="coin")
    op.alter_column("duels", "is_going_first", new_column_name="first_or_second")
    # ### end Alembic commands ###
