"""Add email to users

Revision ID: 16b01cb8872f
Revises: 5c16ff509f3d
Create Date: 2025-09-26 16:01:10.233199

"""

# revision identifiers, used by Alembic.
revision = "16b01cb8872f"
down_revision = "5c16ff509f3d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
