"""rename_duel_columns_for_schema_alignment

Revision ID: 222d71523879
Revises: 142a04659e9c
Create Date: 2025-10-30 16:00:52.069586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222d71523879'
down_revision = '142a04659e9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duels', sa.Column('result', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('duels', sa.Column('coin', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('duels', sa.Column('first_or_second', sa.Boolean(), nullable=False, server_default='false'))

    op.execute('UPDATE duels SET result = is_win, coin = won_coin_toss, first_or_second = is_going_first')

    op.drop_column('duels', 'is_going_first')
    op.drop_column('duels', 'is_win')
    op.drop_column('duels', 'won_coin_toss')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duels', sa.Column('won_coin_toss', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default='false'))
    op.add_column('duels', sa.Column('is_win', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default='false'))
    op.add_column('duels', sa.Column('is_going_first', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default='false'))

    op.execute('UPDATE duels SET is_win = result, won_coin_toss = coin, is_going_first = first_or_second')

    op.drop_column('duels', 'first_or_second')
    op.drop_column('duels', 'coin')
    op.drop_column('duels', 'result')
    # ### end Alembic commands ###
