"""Add email to users

Revision ID: 4a7012b3be58
Revises: 16b01cb8872f
Create Date: 2025-09-26 16:07:58.003223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7012b3be58'
down_revision = '16b01cb8872f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
