"""Add SharedStatistics model

Revision ID: 4b1bece8c168
Revises: feb8abc110c0
Create Date: 2025-10-05 15:53:32.957353

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4b1bece8c168"
down_revision = "feb8abc110c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shared_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("share_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("game_mode", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shared_statistics_id"), "shared_statistics", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_shared_statistics_share_id"),
        "shared_statistics",
        ["share_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shared_statistics_share_id"), table_name="shared_statistics")
    op.drop_index(op.f("ix_shared_statistics_id"), table_name="shared_statistics")
    op.drop_table("shared_statistics")
    # ### end Alembic commands ###
