"""add_timezone_to_duels

Revision ID: 563a63256df2
Revises: 2081618007e6
Create Date: 2025-10-03 20:01:44.932544

"""

# revision identifiers, used by Alembic.
revision = "563a63256df2"
down_revision = "2081618007e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
