"""Fix timestamp defaults

Revision ID: 57c26f35d278
Revises: 4a7012b3be58
Create Date: 2025-09-26 16:28:11.273684

"""

# revision identifiers, used by Alembic.
revision = "57c26f35d278"
down_revision = "4a7012b3be58"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
