"""add is_opponent to decks

Revision ID: 791d5e4f5a31
Revises: b60f0d109415
Create Date: 2025-09-29 12:13:34.145568

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "791d5e4f5a31"
down_revision = "b60f0d109415"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "decks",
        sa.Column("is_opponent", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("decks", "is_opponent")
    # ### end Alembic commands ###
