"""Add server_default to timestamps

Revision ID: 83290d50b360
Revises: 57c26f35d278
Create Date: 2025-09-26 16:34:26.222051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83290d50b360'
down_revision = '57c26f35d278'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
