"""'add_streamer_mode_to_users'

Revision ID: 9132f966097b
Revises: 563a63256df2
Create Date: 2025-10-05 01:59:05.210700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9132f966097b'
down_revision = '563a63256df2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('streamer_mode', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'streamer_mode')
    op.drop_column('decks', 'active')
    # ### end Alembic commands ###
