"""Add supabase_uuid to users

Revision ID: c1d2e3f4g5h6
Revises: b3c4d5e6f7g8
Create Date: 2026-01-13 12:00:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c1d2e3f4g5h6"
down_revision = "b3c4d5e6f7g8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("supabase_uuid", sa.String(length=36), nullable=True),
    )
    op.create_index(
        op.f("ix_users_supabase_uuid"), "users", ["supabase_uuid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_supabase_uuid"), table_name="users")
    op.drop_column("users", "supabase_uuid")
    # ### end Alembic commands ###
