"""change rate_value and dc_value to float type

Revision ID: c9d8e7f6g5h4
Revises: 563a63256df2
Create Date: 2025-10-30 00:00:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "c9d8e7f6g5h4"
down_revision = "a1b2c3d4e5f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # rate_value と dc_value を Integer から Float に変更
    # PostgreSQLの場合、USING句で型キャストを明示
    op.execute(
        "ALTER TABLE duels ALTER COLUMN rate_value TYPE DOUBLE PRECISION USING rate_value::double precision"
    )
    op.execute(
        "ALTER TABLE duels ALTER COLUMN dc_value TYPE DOUBLE PRECISION USING dc_value::double precision"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Float から Integer に戻す（小数点以下は切り捨て）
    op.execute(
        "ALTER TABLE duels ALTER COLUMN rate_value TYPE INTEGER USING rate_value::integer"
    )
    op.execute(
        "ALTER TABLE duels ALTER COLUMN dc_value TYPE INTEGER USING dc_value::integer"
    )
    # ### end Alembic commands ###
