"""change dc_value to integer type

Revision ID: d1e2f3g4h5i6
Revises: a1b2c3d4e5f8
Create Date: 2025-12-25 00:00:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "d1e2f3g4h5i6"
down_revision = "a1b2c3d4e5f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # dc_value を Float から Integer に変更（切り捨て）
    # PostgreSQLの場合、FLOOR関数で切り捨ててからINTEGER型にキャスト
    op.execute(
        "ALTER TABLE duels ALTER COLUMN dc_value TYPE INTEGER USING FLOOR(dc_value)::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Integer から Float に戻す
    op.execute(
        "ALTER TABLE duels ALTER COLUMN dc_value TYPE DOUBLE PRECISION USING dc_value::double precision"
    )
    # ### end Alembic commands ###
