"""add opponentDeck_id to duels

Revision ID: f853e5404fb3
Revises: 791d5e4f5a31
Create Date: 2025-09-29 12:29:30.647334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f853e5404fb3'
down_revision = '791d5e4f5a31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duels', sa.Column('opponentDeck_id', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duels', 'opponentDeck_id')
    # ### end Alembic commands ###
