"""add_fk_to_opponent_deck

Revision ID: feb8abc110c0
Revises: 58c982173971
Create Date: 2025-10-05 13:25:35.789518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb8abc110c0'
down_revision = '58c982173971'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'duels', 'decks', ['opponentDeck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'duels', type_='foreignkey')
    # ### end Alembic commands ###
