// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util.sync'

import { i18nObject } from 'typesafe-i18n'

export { locales }

export const loadLocaleAsync = async (locale: Locales): Promise<void> => {
  if (loadedLocales[locale]) return

  const module = await (locale === 'ja'
    ? import('./ja')
    : locale === 'en'
      ? import('./en')
      : import('./ko'))

  loadedLocales[locale] = module.default as Translations
  loadFormatters(locale)
}

const loadFormatters = (locale: Locales): void => {
  loadedFormatters[locale] = initFormatters(locale)
}

export const i18n = () => {
  return (locale: Locales) => i18nObject<Locales, Translations>(locale, loadedLocales[locale], loadedFormatters[locale])
}

export const i18nString = (locale: Locales) => {
  return i18nObject<Locales, Translations>(locale, loadedLocales[locale], loadedFormatters[locale])
}
