// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Formatters, Locales, Translations } from './i18n-types'

import ja from './ja'

export const locales: Locales[] = ['en', 'ja', 'ko']

export const loadedLocales: Record<Locales, Translations> = {
  ja: ja as Translations,
  en: {} as Translations,
  ko: {} as Translations,
}

export const loadedFormatters: Record<Locales, Formatters> = {
  ja: initFormatters('ja'),
  en: {} as Formatters,
  ko: {} as Formatters,
}

export const loadLocale = (locale: Locales): void => {
  if (locale === 'ja') {
    loadedLocales['ja'] = ja as Translations
    loadedFormatters['ja'] = initFormatters('ja')
  }
}

export const loadAllLocales = (): void => {
  // This is a placeholder for sync loading
  // In practice, use loadLocaleAsync for lazy loading
}
