// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ja'

export type Locales = 'en' | 'ja' | 'ko'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  common: {
    loading: string
    save: string
    cancel: string
    delete: string
    edit: string
    add: string
    confirm: string
    reset: string
    update: string
    close: string
    error: string
    success: string
    dataFetchError: string
    year: string
    month: string
    noData: string
    required: string
  }
  nav: {
    dashboard: string
    decks: string
    statistics: string
    profile: string
    admin: string
    logout: string
  }
  auth: {
    login: {
      title: string
      email: string
      password: string
      submit: string
      forgotPassword: string
      noAccount: string
      register: string
      termsAgreement: string
      termsLink: string
      termsAgreementEnd: string
      error: string
    }
    register: {
      title: string
      subtitle: string
      username: string
      email: string
      password: string
      confirmPassword: string
      submit: string
      hasAccount: string
      success: string
    }
    forgotPassword: {
      title: string
      description: string
      submit: string
      success: string
      backToLogin: string
    }
    resetPassword: {
      title: string
      newPassword: string
      confirmPassword: string
      submit: string
      success: string
    }
    streamerMode: {
      label: string
      hint: string
    }
  }
  dashboard: {
    title: string
    recentDuels: string
    quickStats: string
    noDuels: string
    recordFirst: string
  }
  decks: {
    title: string
    myDecks: string
    opponentDecks: string
    addDeck: string
    deckName: string
    noDeck: string
    noDeckHint: string
    registeredDate: string
    editDeck: string
    deleteDeck: string
    deleteConfirm: string
    archive: {
      title: string
      description: string
      button: string
      confirm: string
      success: string
    }
    archived: string
    showArchived: string
    hideArchived: string
  }
  duels: {
    title: string
    addDuel: string
    editDuel: string
    deleteDuel: string
    deleteConfirm: string
    myDeck: string
    opponentDeck: string
    result: {
      label: string
      win: string
      lose: string
      draw: string
    }
    turnOrder: {
      label: string
      first: string
      second: string
    }
    coinToss: {
      label: string
      win: string
      lose: string
    }
    gameMode: {
      label: string
      rank: string
      rate: string
      event: string
      dc: string
    }
    memo: string
    playedAt: string
    rateValue: string
    dcValue: string
    saveSuccess: string
    deleteSuccess: string
  }
  statistics: {
    title: string
    filter: {
      title: string
      period: string
      periodMonthly: string
      periodRecent: string
      periodAll: string
      periodRange: string
      recentCount: RequiredParams<'count'>
      rangeStart: string
      rangeEnd: string
      myDeck: string
      allDecks: string
      gameMode: string
      allModes: string
    }
    overview: {
      title: string
      totalMatches: string
      wins: string
      losses: string
      draws: string
      winRate: string
    }
    turnOrder: {
      title: string
      first: string
      second: string
      winRate: string
    }
    coinToss: {
      title: string
      win: string
      lose: string
    }
    matchup: {
      title: string
      opponent: string
      matches: string
      winRate: string
    }
    distribution: {
      title: string
      deckName: string
      count: string
      percentage: string
    }
    rateChart: {
      title: string
    }
    dcChart: {
      title: string
    }
    noData: string
    noDataHint: string
  }
  profile: {
    title: string
    username: string
    email: string
    currentPassword: string
    newPassword: string
    newPasswordHint: string
    confirmPassword: string
    saveSuccess: string
    streamerMode: {
      title: string
      description: string
      enable: string
      emailMaskedHint: string
    }
    experimental: {
      title: string
      badge: string
      screenAnalysis: {
        description: string
        enable: string
      }
    }
    accountDeletion: {
      title: string
      warning: string
      button: string
      confirm: string
      confirmInput: string
    }
    dataManagement: {
      title: string
      description: string
      export: string
      import: string
      exportSuccess: string
      importSuccess: string
      importConfirm: string
    }
  }
  obs: {
    title: string
    description: string
    copyUrl: string
    copySuccess: string
    preview: string
    regenerateToken: string
    regenerateConfirm: string
    noToken: string
    settings: {
      title: string
      period: string
      showWinRate: string
      showRecord: string
      showDeck: string
      showRank: string
      theme: string
      themeLight: string
      themeDark: string
      themeTransparent: string
    }
    ranks: {
      beginner: string
      bronze: string
      silver: string
      gold: string
      platinum: string
      diamond: string
      master: string
    }
  }
  shared: {
    title: string
    description: string
    createLink: string
    copyLink: string
    copySuccess: string
    deleteLink: string
    deleteConfirm: string
    publicStats: string
    viewerCount: string
  }
  validation: {
    required: string
    email: string
    minLength: RequiredParams<'min'>
    maxLength: RequiredParams<'max'>
    passwordMatch: string
    passwordMinLength: string
    username: string
    invalidFormat: string
  }
  admin: {
    title: string
    users: {
      title: string
      totalUsers: string
      activeUsers: string
    }
    maintenance: {
      title: string
      mergeDeck: string
      mergeDescription: string
      sourceDeck: string
      targetDeck: string
      mergeSuccess: string
    }
    statistics: {
      title: string
      comingSoon: string
    }
  }
  help: {
    title: string
    bugReport: string
    featureRequest: string
    contact: string
    twitter: string
    version: string
  }
  language: {
    title: string
    ja: string
    en: string
    ko: string
  }
  theme: {
    title: string
    light: string
    dark: string
    system: string
  }
}

export type TranslationFunctions = {
  common: {
    loading: () => LocalizedString
    save: () => LocalizedString
    cancel: () => LocalizedString
    delete: () => LocalizedString
    edit: () => LocalizedString
    add: () => LocalizedString
    confirm: () => LocalizedString
    reset: () => LocalizedString
    update: () => LocalizedString
    close: () => LocalizedString
    error: () => LocalizedString
    success: () => LocalizedString
    dataFetchError: () => LocalizedString
    year: () => LocalizedString
    month: () => LocalizedString
    noData: () => LocalizedString
    required: () => LocalizedString
  }
  nav: {
    dashboard: () => LocalizedString
    decks: () => LocalizedString
    statistics: () => LocalizedString
    profile: () => LocalizedString
    admin: () => LocalizedString
    logout: () => LocalizedString
  }
  auth: {
    login: {
      title: () => LocalizedString
      email: () => LocalizedString
      password: () => LocalizedString
      submit: () => LocalizedString
      forgotPassword: () => LocalizedString
      noAccount: () => LocalizedString
      register: () => LocalizedString
      termsAgreement: () => LocalizedString
      termsLink: () => LocalizedString
      termsAgreementEnd: () => LocalizedString
      error: () => LocalizedString
    }
    register: {
      title: () => LocalizedString
      subtitle: () => LocalizedString
      username: () => LocalizedString
      email: () => LocalizedString
      password: () => LocalizedString
      confirmPassword: () => LocalizedString
      submit: () => LocalizedString
      hasAccount: () => LocalizedString
      success: () => LocalizedString
    }
    forgotPassword: {
      title: () => LocalizedString
      description: () => LocalizedString
      submit: () => LocalizedString
      success: () => LocalizedString
      backToLogin: () => LocalizedString
    }
    resetPassword: {
      title: () => LocalizedString
      newPassword: () => LocalizedString
      confirmPassword: () => LocalizedString
      submit: () => LocalizedString
      success: () => LocalizedString
    }
    streamerMode: {
      label: () => LocalizedString
      hint: () => LocalizedString
    }
  }
  dashboard: {
    title: () => LocalizedString
    recentDuels: () => LocalizedString
    quickStats: () => LocalizedString
    noDuels: () => LocalizedString
    recordFirst: () => LocalizedString
  }
  decks: {
    title: () => LocalizedString
    myDecks: () => LocalizedString
    opponentDecks: () => LocalizedString
    addDeck: () => LocalizedString
    deckName: () => LocalizedString
    noDeck: () => LocalizedString
    noDeckHint: () => LocalizedString
    registeredDate: () => LocalizedString
    editDeck: () => LocalizedString
    deleteDeck: () => LocalizedString
    deleteConfirm: () => LocalizedString
    archive: {
      title: () => LocalizedString
      description: () => LocalizedString
      button: () => LocalizedString
      confirm: () => LocalizedString
      success: () => LocalizedString
    }
    archived: () => LocalizedString
    showArchived: () => LocalizedString
    hideArchived: () => LocalizedString
  }
  duels: {
    title: () => LocalizedString
    addDuel: () => LocalizedString
    editDuel: () => LocalizedString
    deleteDuel: () => LocalizedString
    deleteConfirm: () => LocalizedString
    myDeck: () => LocalizedString
    opponentDeck: () => LocalizedString
    result: {
      label: () => LocalizedString
      win: () => LocalizedString
      lose: () => LocalizedString
      draw: () => LocalizedString
    }
    turnOrder: {
      label: () => LocalizedString
      first: () => LocalizedString
      second: () => LocalizedString
    }
    coinToss: {
      label: () => LocalizedString
      win: () => LocalizedString
      lose: () => LocalizedString
    }
    gameMode: {
      label: () => LocalizedString
      rank: () => LocalizedString
      rate: () => LocalizedString
      event: () => LocalizedString
      dc: () => LocalizedString
    }
    memo: () => LocalizedString
    playedAt: () => LocalizedString
    rateValue: () => LocalizedString
    dcValue: () => LocalizedString
    saveSuccess: () => LocalizedString
    deleteSuccess: () => LocalizedString
  }
  statistics: {
    title: () => LocalizedString
    filter: {
      title: () => LocalizedString
      period: () => LocalizedString
      periodMonthly: () => LocalizedString
      periodRecent: () => LocalizedString
      periodAll: () => LocalizedString
      periodRange: () => LocalizedString
      recentCount: (arg: { count: unknown }) => LocalizedString
      rangeStart: () => LocalizedString
      rangeEnd: () => LocalizedString
      myDeck: () => LocalizedString
      allDecks: () => LocalizedString
      gameMode: () => LocalizedString
      allModes: () => LocalizedString
    }
    overview: {
      title: () => LocalizedString
      totalMatches: () => LocalizedString
      wins: () => LocalizedString
      losses: () => LocalizedString
      draws: () => LocalizedString
      winRate: () => LocalizedString
    }
    turnOrder: {
      title: () => LocalizedString
      first: () => LocalizedString
      second: () => LocalizedString
      winRate: () => LocalizedString
    }
    coinToss: {
      title: () => LocalizedString
      win: () => LocalizedString
      lose: () => LocalizedString
    }
    matchup: {
      title: () => LocalizedString
      opponent: () => LocalizedString
      matches: () => LocalizedString
      winRate: () => LocalizedString
    }
    distribution: {
      title: () => LocalizedString
      deckName: () => LocalizedString
      count: () => LocalizedString
      percentage: () => LocalizedString
    }
    rateChart: {
      title: () => LocalizedString
    }
    dcChart: {
      title: () => LocalizedString
    }
    noData: () => LocalizedString
    noDataHint: () => LocalizedString
  }
  profile: {
    title: () => LocalizedString
    username: () => LocalizedString
    email: () => LocalizedString
    currentPassword: () => LocalizedString
    newPassword: () => LocalizedString
    newPasswordHint: () => LocalizedString
    confirmPassword: () => LocalizedString
    saveSuccess: () => LocalizedString
    streamerMode: {
      title: () => LocalizedString
      description: () => LocalizedString
      enable: () => LocalizedString
      emailMaskedHint: () => LocalizedString
    }
    experimental: {
      title: () => LocalizedString
      badge: () => LocalizedString
      screenAnalysis: {
        description: () => LocalizedString
        enable: () => LocalizedString
      }
    }
    accountDeletion: {
      title: () => LocalizedString
      warning: () => LocalizedString
      button: () => LocalizedString
      confirm: () => LocalizedString
      confirmInput: () => LocalizedString
    }
    dataManagement: {
      title: () => LocalizedString
      description: () => LocalizedString
      export: () => LocalizedString
      import: () => LocalizedString
      exportSuccess: () => LocalizedString
      importSuccess: () => LocalizedString
      importConfirm: () => LocalizedString
    }
  }
  obs: {
    title: () => LocalizedString
    description: () => LocalizedString
    copyUrl: () => LocalizedString
    copySuccess: () => LocalizedString
    preview: () => LocalizedString
    regenerateToken: () => LocalizedString
    regenerateConfirm: () => LocalizedString
    noToken: () => LocalizedString
    settings: {
      title: () => LocalizedString
      period: () => LocalizedString
      showWinRate: () => LocalizedString
      showRecord: () => LocalizedString
      showDeck: () => LocalizedString
      showRank: () => LocalizedString
      theme: () => LocalizedString
      themeLight: () => LocalizedString
      themeDark: () => LocalizedString
      themeTransparent: () => LocalizedString
    }
    ranks: {
      beginner: () => LocalizedString
      bronze: () => LocalizedString
      silver: () => LocalizedString
      gold: () => LocalizedString
      platinum: () => LocalizedString
      diamond: () => LocalizedString
      master: () => LocalizedString
    }
  }
  shared: {
    title: () => LocalizedString
    description: () => LocalizedString
    createLink: () => LocalizedString
    copyLink: () => LocalizedString
    copySuccess: () => LocalizedString
    deleteLink: () => LocalizedString
    deleteConfirm: () => LocalizedString
    publicStats: () => LocalizedString
    viewerCount: () => LocalizedString
  }
  validation: {
    required: () => LocalizedString
    email: () => LocalizedString
    minLength: (arg: { min: number }) => LocalizedString
    maxLength: (arg: { max: number }) => LocalizedString
    passwordMatch: () => LocalizedString
    passwordMinLength: () => LocalizedString
    username: () => LocalizedString
    invalidFormat: () => LocalizedString
  }
  admin: {
    title: () => LocalizedString
    users: {
      title: () => LocalizedString
      totalUsers: () => LocalizedString
      activeUsers: () => LocalizedString
    }
    maintenance: {
      title: () => LocalizedString
      mergeDeck: () => LocalizedString
      mergeDescription: () => LocalizedString
      sourceDeck: () => LocalizedString
      targetDeck: () => LocalizedString
      mergeSuccess: () => LocalizedString
    }
    statistics: {
      title: () => LocalizedString
      comingSoon: () => LocalizedString
    }
  }
  help: {
    title: () => LocalizedString
    bugReport: () => LocalizedString
    featureRequest: () => LocalizedString
    contact: () => LocalizedString
    twitter: () => LocalizedString
    version: () => LocalizedString
  }
  language: {
    title: () => LocalizedString
    ja: () => LocalizedString
    en: () => LocalizedString
    ko: () => LocalizedString
  }
  theme: {
    title: () => LocalizedString
    light: () => LocalizedString
    dark: () => LocalizedString
    system: () => LocalizedString
  }
}

export type Formatters = {}
