// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ja'

export type Locales =
	| 'en'
	| 'ja'
	| 'ko'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * 読​み​込​み​中​.​.​.
		 */
		loading: string
		/**
		 * 保​存
		 */
		save: string
		/**
		 * キ​ャ​ン​セ​ル
		 */
		cancel: string
		/**
		 * 削​除
		 */
		'delete': string
		/**
		 * 編​集
		 */
		edit: string
		/**
		 * 追​加
		 */
		add: string
		/**
		 * 確​認
		 */
		confirm: string
		/**
		 * リ​セ​ッ​ト
		 */
		reset: string
		/**
		 * 更​新
		 */
		update: string
		/**
		 * 閉​じ​る
		 */
		close: string
		/**
		 * エ​ラ​ー​が​発​生​し​ま​し​た
		 */
		error: string
		/**
		 * 不​明​な​エ​ラ​ー​が​発​生​し​ま​し​た
		 */
		unknownError: string
		/**
		 * 成​功​し​ま​し​た
		 */
		success: string
		/**
		 * デ​ー​タ​の​取​得​に​失​敗​し​ま​し​た
		 */
		dataFetchError: string
		/**
		 * 年
		 */
		year: string
		/**
		 * 月
		 */
		month: string
		/**
		 * デ​ー​タ​が​あ​り​ま​せ​ん
		 */
		noData: string
		/**
		 * 必​須
		 */
		required: string
		screenCapture: {
			/**
			 * テ​ン​プ​レ​ー​ト​読​み​込​み​失​敗
			 */
			templateLoadError: string
			/**
			 * 画​面​共​有​の​開​始​に​失​敗​し​ま​し​た
			 */
			startError: string
		}
	}
	nav: {
		/**
		 * ダ​ッ​シ​ュ​ボ​ー​ド
		 */
		dashboard: string
		/**
		 * デ​ッ​キ​管​理
		 */
		decks: string
		/**
		 * 統​計
		 */
		statistics: string
		/**
		 * プ​ロ​フ​ィ​ー​ル
		 */
		profile: string
		/**
		 * 管​理​者​画​面
		 */
		admin: string
		/**
		 * フ​ィ​ー​ド​バ​ッ​ク
		 */
		feedback: string
		/**
		 * ロ​グ​ア​ウ​ト
		 */
		logout: string
	}
	auth: {
		/**
		 * 認​証​状​態​を​確​認​中​.​.​.
		 */
		checkingStatus: string
		login: {
			/**
			 * ロ​グ​イ​ン
			 */
			title: string
			/**
			 * メ​ー​ル​ア​ド​レ​ス
			 */
			email: string
			/**
			 * パ​ス​ワ​ー​ド
			 */
			password: string
			/**
			 * ロ​グ​イ​ン
			 */
			submit: string
			/**
			 * パ​ス​ワ​ー​ド​を​忘​れ​た​場​合
			 */
			forgotPassword: string
			/**
			 * ア​カ​ウ​ン​ト​を​お​持​ち​で​な​い​方​は
			 */
			noAccount: string
			/**
			 * 新​規​登​録
			 */
			register: string
			/**
			 * ロ​グ​イ​ン​す​る​こ​と​で
			 */
			termsAgreement: string
			/**
			 * 利​用​規​約
			 */
			termsLink: string
			/**
			 * に​同​意​し​た​も​の​と​み​な​さ​れ​ま​す
			 */
			termsAgreementEnd: string
			/**
			 * 利​用​規​約
			 */
			termsTitle: string
			/**
			 * メ​ー​ル​ア​ド​レ​ス​ま​た​は​パ​ス​ワ​ー​ド​が​正​し​く​あ​り​ま​せ​ん
			 */
			error: string
			/**
			 * ロ​グ​イ​ン​に​成​功​し​ま​し​た
			 */
			successMessage: string
			/**
			 * ま​た​は
			 */
			orDivider: string
			/**
			 * G​o​o​g​l​e​で​ロ​グ​イ​ン
			 */
			oauthGoogle: string
			/**
			 * D​i​s​c​o​r​d​で​ロ​グ​イ​ン
			 */
			oauthDiscord: string
			features: {
				/**
				 * 詳​細​な​統​計​分​析
				 */
				statistics: string
				/**
				 * デ​ッ​キ​管​理​・​相​性​分​析
				 */
				deckManagement: string
				/**
				 * O​B​S​配​信​連​携
				 */
				obsIntegration: string
			}
		}
		register: {
			/**
			 * 新​規​登​録
			 */
			title: string
			/**
			 * C​r​e​a​t​e​ ​Y​o​u​r​ ​A​c​c​o​u​n​t
			 */
			subtitle: string
			/**
			 * ユ​ー​ザ​ー​名
			 */
			username: string
			/**
			 * メ​ー​ル​ア​ド​レ​ス
			 */
			email: string
			/**
			 * パ​ス​ワ​ー​ド
			 */
			password: string
			/**
			 * パ​ス​ワ​ー​ド​（​確​認​）
			 */
			confirmPassword: string
			/**
			 * 新​規​登​録
			 */
			submit: string
			/**
			 * 既​に​ア​カ​ウ​ン​ト​を​お​持​ち​の​方​は
			 */
			hasAccount: string
			/**
			 * ロ​グ​イ​ン
			 */
			login: string
			/**
			 * 登​録​が​完​了​し​ま​し​た​！
			 */
			success: string
			/**
			 * 確​認​メ​ー​ル​を​送​信​し​ま​し​た​。​メ​ー​ル​を​確​認​し​て​ア​カ​ウ​ン​ト​を​有​効​化​し​て​く​だ​さ​い​。
			 */
			successWithConfirmation: string
		}
		forgotPassword: {
			/**
			 * パ​ス​ワ​ー​ド​リ​セ​ッ​ト
			 */
			title: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​t​o​ ​r​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​.
			 */
			subtitle: string
			/**
			 * 登​録​済​み​の​メ​ー​ル​ア​ド​レ​ス​を​入​力​し​て​く​だ​さ​い​。​パ​ス​ワ​ー​ド​リ​セ​ッ​ト​用​の​リ​ン​ク​を​お​送​り​し​ま​す​。
			 */
			description: string
			/**
			 * メ​ー​ル​ア​ド​レ​ス
			 */
			email: string
			/**
			 * 再​設​定​メ​ー​ル​を​送​信
			 */
			submit: string
			/**
			 * パ​ス​ワ​ー​ド​再​設​定​の​案​内​を​メ​ー​ル​で​送​信​し​ま​し​た​。
			 */
			success: string
			/**
			 * パ​ス​ワ​ー​ド​リ​セ​ッ​ト​メ​ー​ル​の​送​信​に​失​敗​し​ま​し​た
			 */
			error: string
			/**
			 * ロ​グ​イ​ン​ペ​ー​ジ​に​戻​る
			 */
			backToLogin: string
		}
		resetPassword: {
			/**
			 * 新​し​い​パ​ス​ワ​ー​ド​を​設​定
			 */
			title: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​n​e​w​ ​p​a​s​s​w​o​r​d​.
			 */
			subtitle: string
			/**
			 * 新​し​い​パ​ス​ワ​ー​ド
			 */
			newPassword: string
			/**
			 * パ​ス​ワ​ー​ド​の​確​認
			 */
			confirmPassword: string
			/**
			 * パ​ス​ワ​ー​ド​を​リ​セ​ッ​ト
			 */
			submit: string
			/**
			 * パ​ス​ワ​ー​ド​が​正​常​に​リ​セ​ッ​ト​さ​れ​ま​し​た​。
			 */
			success: string
			/**
			 * パ​ス​ワ​ー​ド​の​リ​セ​ッ​ト​に​失​敗​し​ま​し​た
			 */
			error: string
			/**
			 * 認​証​情​報​を​確​認​中​.​.​.
			 */
			checkingSession: string
			/**
			 * セ​ッ​シ​ョ​ン​の​取​得​に​失​敗​し​ま​し​た
			 */
			sessionError: string
			/**
			 * パ​ス​ワ​ー​ド​リ​セ​ッ​ト​リ​ン​ク​が​無​効​ま​た​は​期​限​切​れ​で​す
			 */
			invalidLink: string
			/**
			 * ロ​グ​イ​ン​ペ​ー​ジ​に​戻​る
			 */
			backToLogin: string
		}
		streamerMode: {
			/**
			 * 配​信​者​モ​ー​ド
			 */
			label: string
			/**
			 * 入​力​内​容​を​非​表​示​に​し​、​再​ロ​グ​イ​ン​時​に​メ​ー​ル​ア​ド​レ​ス​を​保​持​し​ま​す
			 */
			hint: string
		}
	}
	dashboard: {
		/**
		 * ダ​ッ​シ​ュ​ボ​ー​ド
		 */
		title: string
		/**
		 * 最​近​の​対​戦
		 */
		recentDuels: string
		/**
		 * 今​月​の​成​績
		 */
		quickStats: string
		/**
		 * ま​だ​対​戦​記​録​が​あ​り​ま​せ​ん
		 */
		noDuels: string
		/**
		 * 最​初​の​対​戦​を​記​録​し​ま​し​ょ​う
		 */
		recordFirst: string
		streak: {
			/**
			 * {​c​o​u​n​t​}​連​勝​中
			 * @param {number} count
			 */
			winning: RequiredParams<'count'>
			/**
			 * {​c​o​u​n​t​}​連​敗​中
			 * @param {number} count
			 */
			losing: RequiredParams<'count'>
			/**
			 * 連​勝​/​連​敗​な​し
			 */
			none: string
		}
		emptyState: {
			/**
			 * 最​初​の​対​戦​を​記​録​し​ま​し​ょ​う
			 */
			title: string
			/**
			 * 対​戦​結​果​を​記​録​し​て​、​あ​な​た​の​成​長​を​追​跡​し​ま​し​ょ​う
			 */
			description: string
			/**
			 * 対​戦​を​記​録
			 */
			addButton: string
		}
		streamer: {
			/**
			 * 配​信​用​ポ​ッ​プ​ア​ッ​プ​ウ​ィ​ン​ド​ウ
			 */
			popupWindow: string
			/**
			 * 推​奨
			 */
			recommended: string
			/**
			 * O​B​S​ブ​ラ​ウ​ザ​ソ​ー​ス
			 */
			obsBrowserSource: string
			/**
			 * 廃​止​予​定
			 */
			deprecated: string
			/**
			 * こ​の​機​能​は​将​来​廃​止​予​定​で​す​。​新​し​い​「​配​信​用​ポ​ッ​プ​ア​ッ​プ​ウ​ィ​ン​ド​ウ​」​の​使​用​を​お​勧​め​し​ま​す​。
			 */
			deprecationWarning: string
			/**
			 * O​B​S​の​ブ​ラ​ウ​ザ​ソ​ー​ス​で​統​計​情​報​を​リ​ア​ル​タ​イ​ム​表​示​で​き​ま​す​。
			 */
			obsDescription: string
			/**
			 * O​B​S​ ​U​R​L​を​取​得
			 */
			getObsUrl: string
			/**
			 * 勝​率
			 */
			winRate: string
			/**
			 * 先​攻​勝​率
			 */
			firstWinRate: string
			/**
			 * 後​攻​勝​率
			 */
			secondWinRate: string
			/**
			 * コ​イ​ン​勝​率
			 */
			coinWinRate: string
			/**
			 * 先​攻​率
			 */
			firstRate: string
		}
		duelEntry: {
			/**
			 * 対​戦​入​力
			 */
			title: string
			/**
			 * ク​イ​ッ​ク​入​力
			 */
			quickEntry: string
			/**
			 * 新​規​追​加​時​の​初​期​値
			 */
			defaultSettings: string
			/**
			 * 先​攻​/​後​攻​の​初​期​値​（​コ​イ​ン​表​時​の​基​準​）
			 */
			defaultTurnTooltip: string
		}
		history: {
			/**
			 * 対​戦​履​歴
			 */
			title: string
			/**
			 * こ​の​期​間​の​対​戦​記​録​は​あ​り​ま​せ​ん
			 */
			noRecords: string
			/**
			 * こ​の​対​戦​記​録​を​削​除​し​て​も​よ​ろ​し​い​で​す​か​？
			 */
			deleteConfirm: string
		}
	}
	decks: {
		/**
		 * デ​ッ​キ​管​理
		 */
		title: string
		/**
		 * 自​分​の​デ​ッ​キ
		 */
		myDecks: string
		/**
		 * 相​手​の​デ​ッ​キ
		 */
		opponentDecks: string
		/**
		 * 追​加
		 */
		addDeck: string
		/**
		 * 自​分​の​デ​ッ​キ​を​追​加
		 */
		addMyDeck: string
		/**
		 * 相​手​の​デ​ッ​キ​を​追​加
		 */
		addOpponentDeck: string
		/**
		 * デ​ッ​キ​名
		 */
		deckName: string
		/**
		 * 例​:​ ​烙​印​、​エ​ル​ド​、​白​き​森
		 */
		deckNamePlaceholder: string
		/**
		 * デ​ッ​キ​が​登​録​さ​れ​て​い​ま​せ​ん
		 */
		noDeck: string
		/**
		 * 「​追​加​」​ボ​タ​ン​か​ら​デ​ッ​キ​を​登​録​し​ま​し​ょ​う
		 */
		noDeckHint: string
		/**
		 * 相​手​の​デ​ッ​キ​が​登​録​さ​れ​て​い​ま​せ​ん
		 */
		noOpponentDeck: string
		/**
		 * 「​追​加​」​ボ​タ​ン​か​ら​相​手​の​デ​ッ​キ​を​登​録​し​ま​し​ょ​う
		 */
		noOpponentDeckHint: string
		/**
		 * 登​録​日
		 */
		registeredDate: string
		/**
		 * デ​ッ​キ​を​編​集
		 */
		editDeck: string
		/**
		 * デ​ッ​キ​を​削​除
		 */
		deleteDeck: string
		/**
		 * こ​の​デ​ッ​キ​を​削​除​し​て​も​よ​ろ​し​い​で​す​か​？
		 */
		deleteConfirm: string
		/**
		 * 同​じ​名​前​の​自​分​の​デ​ッ​キ​が​既​に​存​在​し​ま​す
		 */
		duplicateMyDeck: string
		/**
		 * 同​じ​名​前​の​相​手​の​デ​ッ​キ​が​既​に​存​在​し​ま​す
		 */
		duplicateOpponentDeck: string
		/**
		 * デ​ッ​キ​を​登​録​し​ま​し​た
		 */
		saveSuccess: string
		/**
		 * デ​ッ​キ​を​更​新​し​ま​し​た
		 */
		updateSuccess: string
		/**
		 * デ​ッ​キ​を​削​除​し​ま​し​た
		 */
		deleteSuccess: string
		archive: {
			/**
			 * 月​次​リ​セ​ッ​ト​機​能
			 */
			title: string
			/**
			 * 新​弾​リ​リ​ー​ス​時​な​ど​、​全​デ​ッ​キ​を​一​括​ア​ー​カ​イ​ブ​で​き​ま​す​。​ア​ー​カ​イ​ブ​し​て​も​過​去​の​対​戦​記​録​は​保​持​さ​れ​ま​す​。
			 */
			description: string
			/**
			 * 全​デ​ッ​キ​を​ア​ー​カ​イ​ブ
			 */
			button: string
			/**
			 * 全​て​の​デ​ッ​キ​を​ア​ー​カ​イ​ブ​し​ま​す​か​？
			 */
			confirm: string
			/**
			 * {​c​o​u​n​t​}​件​の​デ​ッ​キ​を​ア​ー​カ​イ​ブ​し​ま​す​か​？​
		​
		​ア​ー​カ​イ​ブ​し​て​も​過​去​の​対​戦​記​録​は​保​持​さ​れ​ま​す​。
			 * @param {number} count
			 */
			confirmWithCount: RequiredParams<'count'>
			/**
			 * 全​デ​ッ​キ​を​ア​ー​カ​イ​ブ​し​ま​し​た
			 */
			success: string
			/**
			 * ア​ー​カ​イ​ブ​す​る​デ​ッ​キ​が​あ​り​ま​せ​ん
			 */
			noDecks: string
			/**
			 * ア​ー​カ​イ​ブ​に​失​敗​し​ま​し​た
			 */
			failed: string
		}
		/**
		 * ア​ー​カ​イ​ブ​済​み
		 */
		archived: string
		/**
		 * ア​ー​カ​イ​ブ​を​表​示
		 */
		showArchived: string
		/**
		 * ア​ー​カ​イ​ブ​を​非​表​示
		 */
		hideArchived: string
	}
	duels: {
		/**
		 * 対​戦​記​録
		 */
		title: string
		/**
		 * 対​戦​を​記​録
		 */
		addDuel: string
		/**
		 * 対​戦​を​編​集
		 */
		editDuel: string
		/**
		 * 対​戦​を​削​除
		 */
		deleteDuel: string
		/**
		 * こ​の​対​戦​記​録​を​削​除​し​て​も​よ​ろ​し​い​で​す​か​？
		 */
		deleteConfirm: string
		/**
		 * 使​用​デ​ッ​キ
		 */
		myDeck: string
		/**
		 * 相​手​デ​ッ​キ
		 */
		opponentDeck: string
		result: {
			/**
			 * 勝​敗
			 */
			label: string
			/**
			 * 勝​ち
			 */
			win: string
			/**
			 * 負​け
			 */
			lose: string
			/**
			 * 引​き​分​け
			 */
			draw: string
		}
		turnOrder: {
			/**
			 * 先​攻​/​後​攻
			 */
			label: string
			/**
			 * 先​攻
			 */
			first: string
			/**
			 * 後​攻
			 */
			second: string
		}
		coinToss: {
			/**
			 * コ​イ​ン
			 */
			label: string
			/**
			 * 表
			 */
			win: string
			/**
			 * 裏
			 */
			lose: string
		}
		gameMode: {
			/**
			 * ゲ​ー​ム​モ​ー​ド
			 */
			label: string
			/**
			 * ラ​ン​ク
			 */
			rank: string
			/**
			 * レ​ー​ト
			 */
			rate: string
			/**
			 * イ​ベ​ン​ト
			 */
			event: string
			/**
			 * D​C
			 */
			dc: string
		}
		/**
		 * 備​考
		 */
		memo: string
		/**
		 * 対​戦​日​時
		 */
		playedAt: string
		/**
		 * レ​ー​ト
		 */
		rateValue: string
		/**
		 * D​C​ポ​イ​ン​ト
		 */
		dcValue: string
		/**
		 * 対​戦​記​録​を​保​存​し​ま​し​た
		 */
		saveSuccess: string
		/**
		 * 対​戦​記​録​を​削​除​し​ま​し​た
		 */
		deleteSuccess: string
		form: {
			/**
			 * 新​規​対​戦​記​録
			 */
			newTitle: string
			/**
			 * 対​戦​記​録​を​編​集
			 */
			editTitle: string
			/**
			 * デ​ッ​キ​を​選​択​ま​た​は​入​力
			 */
			selectOrInputDeck: string
			/**
			 * 新​し​い​デ​ッ​キ​名​を​入​力​で​き​ま​す​（​登​録​時​に​自​動​追​加​）
			 */
			newDeckHint: string
			/**
			 * メ​モ​や​コ​メ​ン​ト​を​入​力
			 */
			memoPlaceholder: string
			/**
			 * 登​録
			 */
			register: string
			/**
			 * 対​戦​記​録​を​自​動​登​録​し​ま​し​た
			 */
			autoRegisterSuccess: string
			/**
			 * 自​動​登​録​に​失​敗​し​ま​し​た
			 */
			autoRegisterFailed: string
			/**
			 * 自​動​登​録​:​ ​使​用​デ​ッ​キ​が​設​定​さ​れ​て​い​ま​せ​ん
			 */
			autoRegisterNoDeck: string
			/**
			 * デ​ッ​キ​の​登​録​に​失​敗​し​ま​し​た
			 */
			deckResolveFailed: string
			/**
			 * 次​の​対​戦​を​待​機​中​.​.​.
			 */
			waitingNext: string
			steps: {
				/**
				 * デ​ッ​キ
				 */
				decks: string
				/**
				 * 対​戦
				 */
				battle: string
				/**
				 * 詳​細
				 */
				details: string
			}
			/**
			 * 次​へ
			 */
			next: string
			/**
			 * 戻​る
			 */
			prev: string
		}
		table: {
			/**
			 * N​o​.
			 */
			noColumn: string
			/**
			 * ラ​ン​ク​/​レ​ー​ト
			 */
			rankOrRate: string
			/**
			 * ア​ク​シ​ョ​ン
			 */
			actions: string
			/**
			 * 対​戦​記​録​が​あ​り​ま​せ​ん
			 */
			noRecords: string
			/**
			 * 「​対​戦​記​録​を​追​加​」​ボ​タ​ン​か​ら​記​録​を​開​始​し​ま​し​ょ​う
			 */
			noRecordsHint: string
			/**
			 * 不​明
			 */
			unknown: string
		}
		screenAnalysis: {
			/**
			 * 画​面​解​析
			 */
			title: string
			/**
			 * ※​テ​ス​ト​機​能
			 */
			testFeature: string
			/**
			 * テ​ン​プ​レ​ー​ト
			 */
			template: string
			/**
			 * M​L
			 */
			ml: string
			/**
			 * 自​動​登​録
			 */
			autoRegister: string
			/**
			 * O​N
			 */
			on: string
			/**
			 * O​F​F
			 */
			off: string
			/**
			 * 開​始
			 */
			start: string
			/**
			 * 停​止
			 */
			stop: string
			/**
			 * 解​析​中
			 */
			running: string
			/**
			 * 停​止​中
			 */
			stopped: string
			/**
			 * 選​択​権​:​ ​検​出
			 */
			turnChoiceDetected: string
			/**
			 * 選​択​権​:​ ​未​検​出
			 */
			turnChoiceNotDetected: string
			/**
			 * 勝​敗
			 */
			resultLabel: string
			/**
			 * 未​検​出
			 */
			notDetected: string
			/**
			 * 登​録​済
			 */
			registered: string
			/**
			 * 登​録​可
			 */
			canRegister: string
			/**
			 * 後​攻​に​切​替
			 */
			switchToSecond: string
			/**
			 * マ​ス​タ​ー​デ​ュ​エ​ル​の​ウ​ィ​ン​ド​ウ​を​選​択​し​て​、​画​面​を​自​動​解​析​し​ま​す​。​勝​敗​結​果​を​検​出​す​る​と​自​動​で​対​戦​記​録​を​登​録​で​き​ま​す​。
			 */
			description: string
			/**
			 * テ​ン​プ​レ​ー​ト​マ​ッ​チ​ン​グ
			 */
			templateMode: string
			/**
			 * 機​械​学​習​(​T​F​.​j​s​)
			 */
			mlMode: string
			/**
			 * モ​ー​ド​で​解​析​し​ま​す​。
			 */
			modeDescription: string
			/**
			 * テ​ン​プ​レ​未​設​定
			 */
			missingTemplate: string
			/**
			 * 学​習​デ​ー​タ​保​存​先​フ​ォ​ル​ダ​を​設​定​し​ま​し​た
			 */
			trainingFolderSet: string
			/**
			 * フ​ォ​ル​ダ​の​選​択​が​キ​ャ​ン​セ​ル​さ​れ​ま​し​た
			 */
			trainingFolderCancelled: string
			/**
			 * 学​習​デ​ー​タ​を​保​存​し​ま​し​た
			 */
			trainingDataSaved: string
		}
	}
	statistics: {
		/**
		 * 統​計​情​報
		 */
		title: string
		filter: {
			/**
			 * 統​計​フ​ィ​ル​タ​ー
			 */
			title: string
			/**
			 * 期​間
			 */
			period: string
			/**
			 * 月​別
			 */
			periodMonthly: string
			/**
			 * 直​近
			 */
			periodRecent: string
			/**
			 * 全​期​間
			 */
			periodAll: string
			/**
			 * 範​囲​指​定
			 */
			periodRange: string
			/**
			 * 直​近​{​c​o​u​n​t​}​件
			 * @param {unknown} count
			 */
			recentCount: RequiredParams<'count'>
			/**
			 * 開​始​（​試​合​目​）
			 */
			rangeStart: string
			/**
			 * 終​了​（​試​合​目​）
			 */
			rangeEnd: string
			/**
			 * 自​分​の​デ​ッ​キ
			 */
			myDeck: string
			/**
			 * 全​て​の​デ​ッ​キ
			 */
			allDecks: string
			/**
			 * ゲ​ー​ム​モ​ー​ド
			 */
			gameMode: string
			/**
			 * 全​モ​ー​ド
			 */
			allModes: string
		}
		overview: {
			/**
			 * 総​合​成​績
			 */
			title: string
			/**
			 * 総​対​戦​数
			 */
			totalMatches: string
			/**
			 * 勝​利
			 */
			wins: string
			/**
			 * 敗​北
			 */
			losses: string
			/**
			 * 引​き​分​け
			 */
			draws: string
			/**
			 * 勝​率
			 */
			winRate: string
		}
		turnOrder: {
			/**
			 * 先​攻​/​後​攻​別​成​績
			 */
			title: string
			/**
			 * 先​攻
			 */
			first: string
			/**
			 * 後​攻
			 */
			second: string
			/**
			 * 勝​率
			 */
			winRate: string
		}
		coinToss: {
			/**
			 * コ​イ​ン​ト​ス​別​成​績
			 */
			title: string
			/**
			 * 勝​ち
			 */
			win: string
			/**
			 * 負​け
			 */
			lose: string
		}
		matchup: {
			/**
			 * デ​ッ​キ​相​性​表
			 */
			title: string
			/**
			 * 使​用​デ​ッ​キ
			 */
			myDeck: string
			/**
			 * 相​手​デ​ッ​キ
			 */
			opponent: string
			/**
			 * 対​戦​数
			 */
			matches: string
			/**
			 * 勝​率
			 */
			winRate: string
			/**
			 * 先​攻​勝​率
			 */
			firstWinRate: string
			/**
			 * 後​攻​勝​率
			 */
			secondWinRate: string
			/**
			 * 相​性​デ​ー​タ​が​あ​り​ま​せ​ん
			 */
			noData: string
		}
		distribution: {
			/**
			 * デ​ッ​キ​分​布
			 */
			title: string
			/**
			 * 月​間​デ​ッ​キ​分​布
			 */
			monthlyTitle: string
			/**
			 * デ​ッ​キ​名
			 */
			deckName: string
			/**
			 * 対​戦​数
			 */
			count: string
			/**
			 * 割​合
			 */
			percentage: string
		}
		duelList: {
			/**
			 * 月​間​対​戦​一​覧
			 */
			title: string
			/**
			 * 全​ ​{​c​o​u​n​t​}​ ​件
			 * @param {number} count
			 */
			totalCount: RequiredParams<'count'>
		}
		myDeckWinRates: {
			/**
			 * 自​分​の​デ​ッ​キ​勝​率
			 */
			title: string
		}
		rateChart: {
			/**
			 * レ​ー​ト​推​移
			 */
			title: string
		}
		dcChart: {
			/**
			 * D​C​推​移
			 */
			title: string
		}
		/**
		 * デ​ー​タ​が​あ​り​ま​せ​ん
		 */
		noData: string
		/**
		 * 対​戦​を​記​録​す​る​と​統​計​が​表​示​さ​れ​ま​す
		 */
		noDataHint: string
	}
	profile: {
		/**
		 * プ​ロ​フ​ィ​ー​ル​編​集
		 */
		title: string
		/**
		 * ユ​ー​ザ​ー​名
		 */
		username: string
		/**
		 * メ​ー​ル​ア​ド​レ​ス
		 */
		email: string
		/**
		 * 現​在​の​パ​ス​ワ​ー​ド
		 */
		currentPassword: string
		/**
		 * 新​し​い​パ​ス​ワ​ー​ド
		 */
		newPassword: string
		/**
		 * 変​更​す​る​場​合​の​み​入​力​（​8​文​字​以​上​、​7​2​文​字​以​下​）
		 */
		newPasswordHint: string
		/**
		 * 新​し​い​パ​ス​ワ​ー​ド​の​確​認
		 */
		confirmPassword: string
		/**
		 * プ​ロ​フ​ィ​ー​ル​を​更​新​し​ま​し​た
		 */
		saveSuccess: string
		streamerMode: {
			/**
			 * 配​信​者​モ​ー​ド
			 */
			title: string
			/**
			 * 有​効​に​す​る​と​、​ア​プ​リ​内​の​メ​ー​ル​ア​ド​レ​ス​が​自​動​的​に​マ​ス​ク​さ​れ​ま​す​。​配​信​や​録​画​時​の​プ​ラ​イ​バ​シ​ー​保​護​に​便​利​で​す​。
			 */
			description: string
			/**
			 * 配​信​者​モ​ー​ド​を​有​効​に​す​る
			 */
			enable: string
			/**
			 * 配​信​者​モ​ー​ド​が​有​効​な​た​め​、​メ​ー​ル​ア​ド​レ​ス​は​マ​ス​ク​さ​れ​て​い​ま​す
			 */
			emailMaskedHint: string
		}
		experimental: {
			/**
			 * 実​験​的​機​能
			 */
			title: string
			/**
			 * テ​ス​ト
			 */
			badge: string
			screenAnalysis: {
				/**
				 * 画​面​解​析​機​能​を​有​効​に​す​る​と​、​対​戦​記​録​作​成​時​に​画​面​キ​ャ​プ​チ​ャ​に​よ​る​自​動​入​力​機​能​が​使​用​で​き​ま​す​。​こ​の​機​能​は​開​発​中​の​た​め​、​誤​判​定​が​発​生​す​る​可​能​性​が​あ​り​ま​す​。
				 */
				description: string
				/**
				 * 画​面​解​析​機​能​を​有​効​に​す​る
				 */
				enable: string
			}
		}
		accountDeletion: {
			/**
			 * ア​カ​ウ​ン​ト​削​除
			 */
			title: string
			/**
			 * こ​の​操​作​は​元​に​戻​せ​ま​せ​ん​。​ア​カ​ウ​ン​ト​を​削​除​す​る​と​、​す​べ​て​の​デ​ッ​キ​と​対​戦​履​歴​が​完​全​に​削​除​さ​れ​ま​す​。
			 */
			warning: string
			/**
			 * ア​カ​ウ​ン​ト​を​削​除​す​る
			 */
			button: string
			/**
			 * 本​当​に​ア​カ​ウ​ン​ト​を​削​除​し​ま​す​か​？​こ​の​操​作​は​取​り​消​せ​ま​せ​ん​。
			 */
			confirm: string
			/**
			 * 確​認​の​た​め​「​削​除​」​と​入​力​し​て​く​だ​さ​い
			 */
			confirmInput: string
		}
		dataManagement: {
			/**
			 * デ​ー​タ​管​理
			 */
			title: string
			/**
			 * 全​デ​ー​タ​を​C​S​V​フ​ァ​イ​ル​と​し​て​エ​ク​ス​ポ​ー​ト​（​バ​ッ​ク​ア​ッ​プ​）​し​た​り​、​イ​ン​ポ​ー​ト​（​復​元​）​し​た​り​で​き​ま​す​。
			 */
			description: string
			/**
			 * エ​ク​ス​ポ​ー​ト
			 */
			'export': string
			/**
			 * イ​ン​ポ​ー​ト
			 */
			'import': string
			/**
			 * デ​ー​タ​を​エ​ク​ス​ポ​ー​ト​し​ま​し​た
			 */
			exportSuccess: string
			/**
			 * デ​ー​タ​を​イ​ン​ポ​ー​ト​し​ま​し​た
			 */
			importSuccess: string
			/**
			 * イ​ン​ポ​ー​ト​す​る​と​既​存​の​デ​ー​タ​が​上​書​き​さ​れ​ま​す​。​続​行​し​ま​す​か​？
			 */
			importConfirm: string
		}
	}
	obs: {
		/**
		 * O​B​S​オ​ー​バ​ー​レ​イ
		 */
		title: string
		/**
		 * O​B​S​ ​S​t​u​d​i​o​な​ど​の​配​信​ソ​フ​ト​で​使​用​で​き​る​オ​ー​バ​ー​レ​イ​U​R​L​を​生​成​し​ま​す​。​ブ​ラ​ウ​ザ​ソ​ー​ス​と​し​て​追​加​し​て​く​だ​さ​い​。
		 */
		description: string
		/**
		 * U​R​L​を​コ​ピ​ー
		 */
		copyUrl: string
		/**
		 * U​R​L​を​コ​ピ​ー​し​ま​し​た
		 */
		copySuccess: string
		/**
		 * プ​レ​ビ​ュ​ー
		 */
		preview: string
		/**
		 * ト​ー​ク​ン​を​再​生​成
		 */
		regenerateToken: string
		/**
		 * ト​ー​ク​ン​を​再​生​成​す​る​と​、​現​在​の​U​R​L​は​使​用​で​き​な​く​な​り​ま​す​。​続​行​し​ま​す​か​？
		 */
		regenerateConfirm: string
		/**
		 * U​R​L​に​ト​ー​ク​ン​が​含​ま​れ​て​い​ま​せ​ん
		 */
		noToken: string
		settings: {
			/**
			 * 表​示​設​定
			 */
			title: string
			/**
			 * 表​示​期​間
			 */
			period: string
			/**
			 * 勝​率​を​表​示
			 */
			showWinRate: string
			/**
			 * 戦​績​を​表​示
			 */
			showRecord: string
			/**
			 * デ​ッ​キ​名​を​表​示
			 */
			showDeck: string
			/**
			 * ラ​ン​ク​を​表​示
			 */
			showRank: string
			/**
			 * テ​ー​マ
			 */
			theme: string
			/**
			 * ラ​イ​ト
			 */
			themeLight: string
			/**
			 * ダ​ー​ク
			 */
			themeDark: string
			/**
			 * 透​過
			 */
			themeTransparent: string
		}
		ranks: {
			/**
			 * ビ​ギ​ナ​ー
			 */
			beginner: string
			/**
			 * ブ​ロ​ン​ズ
			 */
			bronze: string
			/**
			 * シ​ル​バ​ー
			 */
			silver: string
			/**
			 * ゴ​ー​ル​ド
			 */
			gold: string
			/**
			 * プ​ラ​チ​ナ
			 */
			platinum: string
			/**
			 * ダ​イ​ヤ
			 */
			diamond: string
			/**
			 * マ​ス​タ​ー
			 */
			master: string
			/**
			 * 不​明
			 */
			unknown: string
		}
		streamerPopup: {
			/**
			 * 配​信​用​ポ​ッ​プ​ア​ッ​プ​設​定
			 */
			title: string
			/**
			 * ゲ​ー​ム​モ​ー​ド
			 */
			gameMode: string
			/**
			 * レ​イ​ア​ウ​ト
			 */
			layout: string
			/**
			 * 自​動​更​新​間​隔
			 */
			refreshInterval: string
			/**
			 * 表​示​項​目
			 */
			displayItems: string
			/**
			 * {​c​o​u​n​t​}​個​選​択​中
			 * @param {number} count
			 */
			displayItemsCount: RequiredParams<'count'>
			/**
			 * ポ​ッ​プ​ア​ッ​プ​を​開​く
			 */
			openPopup: string
			gameModes: {
				/**
				 * ラ​ン​ク​マ​ッ​チ
				 */
				rank: string
				/**
				 * レ​ー​ト​マ​ッ​チ
				 */
				rate: string
				/**
				 * イ​ベ​ン​ト
				 */
				event: string
				/**
				 * デ​ュ​エ​リ​ス​ト​カ​ッ​プ
				 */
				dc: string
			}
			layouts: {
				/**
				 * グ​リ​ッ​ド​（​自​動​調​整​）
				 */
				grid: string
				/**
				 * 横​並​び
				 */
				horizontal: string
				/**
				 * 縦​並​び
				 */
				vertical: string
			}
			intervals: {
				/**
				 * 1​0​秒
				 */
				sec10: string
				/**
				 * 3​0​秒
				 */
				sec30: string
				/**
				 * 1​分
				 */
				min1: string
			}
			/**
			 * 統​計​期​間
			 */
			statsPeriod: string
			statsPeriods: {
				/**
				 * 当​月
				 */
				monthly: string
				/**
				 * 配​信​開​始​か​ら
				 */
				session: string
			}
			items: {
				/**
				 * 使​用​デ​ッ​キ
				 */
				currentDeck: string
				/**
				 * ラ​ン​ク​/​レ​ー​ト​/​D​C​（​ゲ​ー​ム​モ​ー​ド​に​連​動​）
				 */
				gameModeValue: string
				/**
				 * 総​試​合​数
				 */
				totalDuels: string
				/**
				 * 勝​率
				 */
				winRate: string
				/**
				 * 先​攻​勝​率
				 */
				firstTurnWinRate: string
				/**
				 * 後​攻​勝​率
				 */
				secondTurnWinRate: string
				/**
				 * コ​イ​ン​勝​率
				 */
				coinWinRate: string
				/**
				 * 先​攻​率
				 */
				goFirstRate: string
				/**
				 * ラ​ン​ク
				 */
				rank: string
				/**
				 * レ​ー​ト
				 */
				rate: string
				/**
				 * D​C
				 */
				dc: string
				/**
				 * 未​設​定
				 */
				notSet: string
			}
			/**
			 * ロ​グ​イ​ン​が​必​要​で​す
			 */
			loginRequired: string
			/**
			 * ロ​グ​イ​ン​状​態​で​こ​の​ペ​ー​ジ​を​開​い​て​く​だ​さ​い
			 */
			loginRequiredDetail: string
			chromaKey: {
				/**
				 * ク​ロ​マ​キ​ー​背​景
				 */
				title: string
				/**
				 * ウ​ィ​ン​ド​ウ​キ​ャ​プ​チ​ャ​時​に​O​B​S​の​ク​ロ​マ​キ​ー​フ​ィ​ル​タ​ー​で​背​景​を​透​過​で​き​ま​す​。
				 */
				description: string
				/**
				 * 通​常
				 */
				none: string
				/**
				 * グ​リ​ー​ン
				 */
				green: string
				/**
				 * ブ​ル​ー
				 */
				blue: string
			}
		}
		configPanel: {
			/**
			 * O​B​S​連​携​設​定
			 */
			title: string
			/**
			 * O​B​S​の​ブ​ラ​ウ​ザ​ソ​ー​ス​で​統​計​情​報​を​リ​ア​ル​タ​イ​ム​で​オ​ー​バ​ー​レ​イ​表​示​で​き​ま​す​。​表​示​す​る​項​目​と​集​計​期​間​を​カ​ス​タ​マ​イ​ズ​で​き​ま​す​。
			 */
			description: string
			/**
			 * 集​計​期​間
			 */
			periodType: string
			/**
			 * 月​間
			 */
			periodMonthly: string
			/**
			 * 直​近​N​戦
			 */
			periodRecent: string
			/**
			 * 累​計
			 */
			periodFromStart: string
			/**
			 * 年
			 */
			year: string
			/**
			 * 月
			 */
			month: string
			/**
			 * 表​示​す​る​試​合​数
			 */
			matchCount: string
			/**
			 * ゲ​ー​ム​モ​ー​ド​（​任​意​）
			 */
			gameModeOptional: string
			/**
			 * 表​示​す​る​項​目​を​選​択​（​ド​ラ​ッ​グ​で​並​び​替​え​可​能​）
			 */
			displayItemsTitle: string
			/**
			 * 更​新​間​隔​（​ミ​リ​秒​）
			 */
			refreshIntervalMs: string
			/**
			 * O​B​S​で​の​設​定​方​法​：
			 */
			obsSetupGuide: string
			/**
			 * O​B​S​で​「​ソ​ー​ス​」​→​「​+​」​→​「​ブ​ラ​ウ​ザ​」​を​選​択
			 */
			obsStep1: string
			/**
			 * 以​下​の​U​R​L​を​コ​ピ​ー​し​て​「​U​R​L​」​欄​に​貼​り​付​け
			 */
			obsStep2: string
			/**
			 * カ​ス​タ​ム​C​S​S​で​背​景​を​透​過​:
			 */
			obsStep4: string
			/**
			 * O​B​S​用​U​R​L
			 */
			obsUrl: string
			/**
			 * ※​ ​こ​の​U​R​L​に​は​認​証​ト​ー​ク​ン​が​含​ま​れ​て​い​ま​す​。​他​人​と​共​有​し​な​い​で​く​だ​さ​い​。
			 */
			urlWarning: string
			/**
			 * 幅​:​ ​8​0​0​p​x​、​高​さ​:​ ​6​0​0​p​x​ ​を​推​奨
			 */
			recommendedSizeGrid: string
			/**
			 * 幅​:​ ​1​9​2​0​p​x​、​高​さ​:​ ​2​0​0​p​x​ ​を​推​奨​（​下​部​に​配​置​）
			 */
			recommendedSizeHorizontal: string
			/**
			 * 幅​:​ ​2​5​0​p​x​、​高​さ​:​ ​1​0​8​0​p​x​ ​を​推​奨​（​右​端​に​配​置​）
			 */
			recommendedSizeVertical: string
			/**
			 * O​B​S​用​ト​ー​ク​ン​の​取​得​に​失​敗​し​ま​し​た​。​再​ロ​グ​イ​ン​し​て​く​だ​さ​い
			 */
			tokenFetchError: string
			/**
			 * U​R​L​を​コ​ピ​ー​し​ま​し​た
			 */
			urlCopySuccess: string
			/**
			 * U​R​L​の​コ​ピ​ー​に​失​敗​し​ま​し​た
			 */
			urlCopyError: string
			items: {
				/**
				 * 勝​率
				 */
				winRate: string
				/**
				 * 総​試​合​数
				 */
				record: string
				/**
				 * 使​用​デ​ッ​キ
				 */
				deck: string
				/**
				 * 現​在​の​ラ​ン​ク
				 */
				rank: string
				/**
				 * 現​在​の​レ​ー​ト
				 */
				rate: string
				/**
				 * 現​在​の​D​C
				 */
				dc: string
				/**
				 * 先​攻​勝​率
				 */
				firstTurnWinRate: string
				/**
				 * 後​攻​勝​率
				 */
				secondTurnWinRate: string
				/**
				 * コ​イ​ン​勝​率
				 */
				coinTossWinRate: string
				/**
				 * 先​攻​率
				 */
				goFirstRate: string
			}
		}
	}
	shared: {
		/**
		 * 統​計​を​共​有
		 */
		title: string
		/**
		 * 統​計​情​報​を​公​開​U​R​L​で​共​有​で​き​ま​す​。
		 */
		description: string
		/**
		 * 共​有​リ​ン​ク​を​作​成
		 */
		createLink: string
		/**
		 * リ​ン​ク​を​コ​ピ​ー
		 */
		copyLink: string
		/**
		 * リ​ン​ク​を​コ​ピ​ー​し​ま​し​た
		 */
		copySuccess: string
		/**
		 * 共​有​を​停​止
		 */
		deleteLink: string
		/**
		 * 共​有​を​停​止​す​る​と​、​こ​の​U​R​L​は​使​用​で​き​な​く​な​り​ま​す​。​続​行​し​ま​す​か​？
		 */
		deleteConfirm: string
		/**
		 * 公​開​統​計
		 */
		publicStats: string
		/**
		 * 閲​覧​数
		 */
		viewerCount: string
		/**
		 * 共​有​リ​ン​ク​が​生​成​さ​れ​ま​し​た​！
		 */
		createSuccess: string
		/**
		 * 共​有​リ​ン​ク​の​生​成​に​失​敗​し​ま​し​た​。
		 */
		createError: string
		/**
		 * 共​有​統​計​デ​ー​タ​の​取​得​に​失​敗​し​ま​し​た​。
		 */
		fetchError: string
		/**
		 * 共​有​リ​ン​ク​が​削​除​さ​れ​ま​し​た​。
		 */
		deleteSuccess: string
		/**
		 * 共​有​リ​ン​ク​の​削​除​に​失​敗​し​ま​し​た​。
		 */
		deleteError: string
		dialog: {
			/**
			 * 共​有​リ​ン​ク​を​生​成
			 */
			title: string
			/**
			 * 有​効​期​限​ ​(​Y​Y​Y​Y​-​M​M​-​D​D​,​ ​オ​プ​シ​ョ​ン​)
			 */
			expiresAt: string
			/**
			 * リ​ン​ク​を​生​成
			 */
			generateButton: string
			/**
			 * 有​効​期​限​の​日​付​形​式​が​不​正​で​す​。​Y​Y​Y​Y​-​M​M​-​D​D​ ​形​式​で​入​力​し​て​く​だ​さ​い​。
			 */
			invalidDateFormat: string
			/**
			 * 有​効​期​限​の​日​付​が​不​正​で​す​。​存​在​し​な​い​日​付​が​入​力​さ​れ​ま​し​た​。
			 */
			invalidDate: string
			/**
			 * リ​ン​ク​の​コ​ピ​ー​に​失​敗​し​ま​し​た​。​手​動​で​コ​ピ​ー​し​て​く​だ​さ​い​。
			 */
			copyFailed: string
		}
	}
	validation: {
		/**
		 * 必​須​項​目​で​す
		 */
		required: string
		/**
		 * 有​効​な​メ​ー​ル​ア​ド​レ​ス​を​入​力​し​て​く​だ​さ​い
		 */
		email: string
		/**
		 * {​m​i​n​}​文​字​以​上​で​入​力​し​て​く​だ​さ​い
		 * @param {number} min
		 */
		minLength: RequiredParams<'min'>
		/**
		 * {​m​a​x​}​文​字​以​内​で​入​力​し​て​く​だ​さ​い
		 * @param {number} max
		 */
		maxLength: RequiredParams<'max'>
		/**
		 * パ​ス​ワ​ー​ド​が​一​致​し​ま​せ​ん
		 */
		passwordMatch: string
		/**
		 * パ​ス​ワ​ー​ド​は​8​文​字​以​上​で​入​力​し​て​く​だ​さ​い
		 */
		passwordMinLength: string
		/**
		 * パ​ス​ワ​ー​ド​は​6​文​字​以​上​で​入​力​し​て​く​だ​さ​い
		 */
		passwordMinLength6: string
		/**
		 * ユ​ー​ザ​ー​名​は​3​文​字​以​上​で​入​力​し​て​く​だ​さ​い
		 */
		username: string
		/**
		 * 形​式​が​正​し​く​あ​り​ま​せ​ん
		 */
		invalidFormat: string
		/**
		 * 予​期​せ​ぬ​エ​ラ​ー​が​発​生​し​ま​し​た
		 */
		unexpectedError: string
		/**
		 * 0​以​上​の​数​値​を​入​力​し​て​く​だ​さ​い
		 */
		positiveNumber: string
		/**
		 * 整​数​を​入​力​し​て​く​だ​さ​い
		 */
		integer: string
	}
	admin: {
		/**
		 * 管​理​者​画​面
		 */
		title: string
		users: {
			/**
			 * ユ​ー​ザ​ー​管​理
			 */
			title: string
			/**
			 * 総​ユ​ー​ザ​ー​数
			 */
			totalUsers: string
			/**
			 * ア​ク​テ​ィ​ブ​ユ​ー​ザ​ー
			 */
			activeUsers: string
		}
		maintenance: {
			/**
			 * メ​ン​テ​ナ​ン​ス
			 */
			title: string
			/**
			 * ス​キ​ャ​ン
			 */
			scan: string
			/**
			 * ク​リ​ー​ン​ア​ッ​プ
			 */
			cleanup: string
			/**
			 * 一​括​削​除
			 */
			bulkDelete: string
			/**
			 * 実​行
			 */
			execute: string
			/**
			 * 警​告​：
			 */
			warning: string
			/**
			 * こ​の​操​作​は​取​り​消​せ​ま​せ​ん​。
			 */
			cannotUndo: string
			/**
			 * 続​行​し​ま​す​か​？
			 */
			confirmProceed: string
			/**
			 * 完​了
			 */
			success: string
			/**
			 * 失​敗
			 */
			failed: string
			/**
			 * ス​キ​ャ​ン​に​失​敗​し​ま​し​た
			 */
			scanError: string
			/**
			 * ク​リ​ー​ン​ア​ッ​プ​に​失​敗​し​ま​し​た
			 */
			cleanupError: string
			mergeDeck: {
				/**
				 * ア​ー​カ​イ​ブ​デ​ッ​キ​の​マ​ー​ジ
				 */
				title: string
				/**
				 * 同​じ​名​前​の​ア​ー​カ​イ​ブ​済​み​デ​ッ​キ​を​現​在​の​デ​ッ​キ​に​マ​ー​ジ​し​ま​す​。
				 */
				description: string
				/**
				 * マ​ー​ジ​を​実​行
				 */
				button: string
				/**
				 * マ​ー​ジ​の​確​認
				 */
				confirmTitle: string
				/**
				 * ア​ー​カ​イ​ブ​さ​れ​た​デ​ッ​キ​を​同​名​の​現​在​の​デ​ッ​キ​に​マ​ー​ジ​し​ま​す​。
				 */
				confirmMessage: string
				/**
				 * デ​ッ​キ​の​マ​ー​ジ​が​完​了​し​ま​し​た
				 */
				success: string
				/**
				 * デ​ッ​キ​の​マ​ー​ジ​に​失​敗​し​ま​し​た
				 */
				error: string
			}
			orphanedDecks: {
				/**
				 * 孤​立​デ​ッ​キ​の​ク​リ​ー​ン​ア​ッ​プ
				 */
				title: string
				/**
				 * 対​戦​記​録​か​ら​参​照​さ​れ​て​い​な​い​相​手​デ​ッ​キ​を​検​出​・​削​除​し​ま​す​。
				 */
				description: string
				/**
				 * 件​の​孤​立​デ​ッ​キ​が​見​つ​か​り​ま​し​た
				 */
				found: string
				/**
				 * 孤​立​デ​ッ​キ​の​削​除
				 */
				confirmTitle: string
				/**
				 * 件​の​孤​立​デ​ッ​キ​を​削​除​し​ま​す​。
				 */
				confirmMessage: string
			}
			sharedUrls: {
				/**
				 * 共​有​U​R​L​の​ク​リ​ー​ン​ア​ッ​プ
				 */
				title: string
				orphaned: {
					/**
					 * 孤​立​し​た​共​有​U​R​L
					 */
					title: string
					/**
					 * 削​除​さ​れ​た​ユ​ー​ザ​ー​に​紐​づ​く​共​有​U​R​L​を​検​出​・​削​除​し​ま​す​。
					 */
					description: string
					/**
					 * 件​の​孤​立​し​た​共​有​U​R​L​が​見​つ​か​り​ま​し​た
					 */
					found: string
					/**
					 * 孤​立​U​R​L​の​削​除
					 */
					confirmTitle: string
					/**
					 * 件​の​孤​立​し​た​共​有​U​R​L​を​削​除​し​ま​す​。
					 */
					confirmMessage: string
				}
				expired: {
					/**
					 * 期​限​切​れ​共​有​U​R​L
					 */
					title: string
					/**
					 * 有​効​期​限​が​切​れ​た​共​有​U​R​L​を​検​出​・​削​除​し​ま​す​。
					 */
					description: string
					/**
					 * 件​の​期​限​切​れ​共​有​U​R​L​が​見​つ​か​り​ま​し​た
					 */
					found: string
					/**
					 * 最​も​古​い​期​限​切​れ
					 */
					oldest: string
					/**
					 * 期​限​切​れ​U​R​L​の​削​除
					 */
					confirmTitle: string
					/**
					 * 件​の​期​限​切​れ​共​有​U​R​L​を​削​除​し​ま​す​。
					 */
					confirmMessage: string
				}
			}
		}
		statistics: {
			/**
			 * シ​ス​テ​ム​統​計
			 */
			title: string
			/**
			 * 総​ユ​ー​ザ​ー​数
			 */
			totalUsers: string
			/**
			 * 今​月
			 */
			thisMonth: string
			/**
			 * 総​デ​ッ​キ​数
			 */
			totalDecks: string
			/**
			 * ア​ク​テ​ィ​ブ​/​ア​ー​カ​イ​ブ
			 */
			activeArchived: string
			/**
			 * 総​対​戦​数
			 */
			totalDuels: string
			/**
			 * 今​月​の​ア​ク​テ​ィ​ブ​ユ​ー​ザ​ー
			 */
			activeUsersThisMonth: string
			/**
			 * ゲ​ー​ム​モ​ー​ド​別​内​訳
			 */
			gameModeBreakdown: string
			/**
			 * 対​戦​数​推​移
			 */
			duelsTimeline: string
			/**
			 * ユ​ー​ザ​ー​登​録​数​推​移
			 */
			userRegistrations: string
			/**
			 * 対​戦​数
			 */
			duelsCount: string
			/**
			 * 新​規​ユ​ー​ザ​ー
			 */
			newUsers: string
		}
		userDetail: {
			/**
			 * 基​本​情​報
			 */
			basicInfo: string
			/**
			 * メ​ー​ル​ア​ド​レ​ス
			 */
			email: string
			/**
			 * 登​録​日
			 */
			registeredAt: string
			/**
			 * 最​終​ロ​グ​イ​ン
			 */
			lastLoginAt: string
			/**
			 * テ​ー​マ
			 */
			theme: string
			/**
			 * 状​態​変​更​理​由
			 */
			statusReason: string
			/**
			 * 利​用​統​計
			 */
			stats: string
			/**
			 * 総​対​戦​数
			 */
			totalDuels: string
			/**
			 * 今​月​の​対​戦
			 */
			thisMonthDuels: string
			/**
			 * 勝​率
			 */
			winRate: string
			/**
			 * 勝​敗
			 */
			winLoss: string
			/**
			 * 自​分​の​デ​ッ​キ
			 */
			playerDecks: string
			/**
			 * 相​手​の​デ​ッ​キ
			 */
			opponentDecks: string
			/**
			 * 機​能​利​用​状​況
			 */
			featureUsage: string
			/**
			 * 配​信​者​モ​ー​ド
			 */
			streamerMode: string
			/**
			 * O​B​S​オ​ー​バ​ー​レ​イ
			 */
			obsOverlay: string
			/**
			 * 統​計​共​有
			 */
			sharedStats: string
			/**
			 * 画​面​分​析
			 */
			screenAnalysis: string
			/**
			 * 状​態​を​変​更
			 */
			changeStatus: string
			/**
			 * パ​ス​ワ​ー​ド​リ​セ​ッ​ト
			 */
			resetPassword: string
			/**
			 * 有​効
			 */
			statusActive: string
			/**
			 * 停​止​中
			 */
			statusSuspended: string
			/**
			 * 削​除​済​み
			 */
			statusDeleted: string
			/**
			 * ア​カ​ウ​ン​ト​状​態​の​変​更
			 */
			changeStatusTitle: string
			/**
			 * {​u​s​e​r​n​a​m​e​}​ ​の​状​態​を​変​更​し​ま​す​。
			 * @param {string} username
			 */
			changeStatusDescription: RequiredParams<'username'>
			/**
			 * 新​し​い​状​態
			 */
			newStatus: string
			/**
			 * 理​由​（​任​意​）
			 */
			reason: string
			/**
			 * 状​態​変​更​の​理​由​を​入​力​し​て​く​だ​さ​い
			 */
			reasonPlaceholder: string
			/**
			 * ア​カ​ウ​ン​ト​を​停​止​す​る​と​、​ユ​ー​ザ​ー​は​ロ​グ​イ​ン​で​き​な​く​な​り​ま​す​。
			 */
			suspendedWarning: string
			/**
			 * ア​カ​ウ​ン​ト​を​削​除​扱​い​に​す​る​と​、​復​旧​が​必​要​に​な​り​ま​す​。
			 */
			deletedWarning: string
		}
		meta: {
			/**
			 * メ​タ​分​析
			 */
			title: string
			/**
			 * 期​間
			 */
			period: string
			/**
			 * ゲ​ー​ム​モ​ー​ド
			 */
			gameMode: string
			/**
			 * 最​小​使​用​回​数
			 */
			minUsage: string
			/**
			 * 7​日​間
			 */
			period7days: string
			/**
			 * 1​4​日​間
			 */
			period14days: string
			/**
			 * 3​0​日​間
			 */
			period30days: string
			/**
			 * 6​0​日​間
			 */
			period60days: string
			/**
			 * 9​0​日​間
			 */
			period90days: string
			/**
			 * 人​気​デ​ッ​キ​ラ​ン​キ​ン​グ
			 */
			popularDecks: string
			/**
			 * デ​ッ​キ​使​用​率​推​移
			 */
			deckTrends: string
			/**
			 * ゲ​ー​ム​モ​ー​ド​別​統​計
			 */
			gameModeStats: string
			/**
			 * 総​対​戦​数
			 */
			totalDuels: string
			/**
			 * デ​ー​タ​が​あ​り​ま​せ​ん
			 */
			noData: string
		}
	}
	help: {
		/**
		 * ヘ​ル​プ
		 */
		title: string
		/**
		 * バ​グ​を​報​告
		 */
		bugReport: string
		/**
		 * 機​能​を​リ​ク​エ​ス​ト
		 */
		featureRequest: string
		/**
		 * お​問​い​合​わ​せ
		 */
		contact: string
		/**
		 * T​w​i​t​t​e​r​/​X
		 */
		twitter: string
		/**
		 * バ​ー​ジ​ョ​ン
		 */
		version: string
	}
	feedback: {
		/**
		 * バ​グ​報​告​、​機​能​要​望​、​お​問​い​合​わ​せ​を​お​待​ち​し​て​お​り​ま​す​。​G​i​t​H​u​b​の​I​s​s​u​e​と​し​て​登​録​さ​れ​ま​す​。
		 */
		intro: string
		tabs: {
			/**
			 * バ​グ​報​告
			 */
			bug: string
			/**
			 * 機​能​要​望
			 */
			enhancement: string
			/**
			 * お​問​い​合​わ​せ
			 */
			contact: string
		}
		form: {
			/**
			 * タ​イ​ト​ル
			 */
			title: string
			/**
			 * 説​明
			 */
			description: string
		}
		bug: {
			/**
			 * バ​グ​の​概​要​を​入​力
			 */
			titlePlaceholder: string
			/**
			 * バ​グ​の​詳​細​を​入​力​し​て​く​だ​さ​い
			 */
			descriptionPlaceholder: string
			/**
			 * 再​現​手​順
			 */
			steps: string
			/**
			 * 1​.​ ​○​○​を​開​く​
		​2​.​ ​○​○​を​ク​リ​ッ​ク​
		​3​.​ ​エ​ラ​ー​が​発​生
			 */
			stepsPlaceholder: string
			/**
			 * 期​待​す​る​動​作
			 */
			expected: string
			/**
			 * 本​来​ど​う​な​る​べ​き​か
			 */
			expectedPlaceholder: string
			/**
			 * 実​際​の​動​作
			 */
			actual: string
			/**
			 * 実​際​に​何​が​起​き​た​か
			 */
			actualPlaceholder: string
			/**
			 * バ​グ​を​報​告​す​る
			 */
			submit: string
		}
		enhancement: {
			/**
			 * 機​能​の​概​要​を​入​力
			 */
			titlePlaceholder: string
			/**
			 * 追​加​し​て​ほ​し​い​機​能​の​詳​細​を​入​力​し​て​く​だ​さ​い
			 */
			descriptionPlaceholder: string
			/**
			 * ユ​ー​ス​ケ​ー​ス
			 */
			useCase: string
			/**
			 * ど​の​よ​う​な​場​面​で​使​い​た​い​か
			 */
			useCasePlaceholder: string
			/**
			 * 機​能​を​要​望​す​る
			 */
			submit: string
		}
		contact: {
			/**
			 * 件​名
			 */
			subject: string
			/**
			 * お​問​い​合​わ​せ​の​件​名​を​入​力
			 */
			subjectPlaceholder: string
			/**
			 * メ​ッ​セ​ー​ジ
			 */
			message: string
			/**
			 * お​問​い​合​わ​せ​内​容​を​入​力​し​て​く​だ​さ​い
			 */
			messagePlaceholder: string
			/**
			 * 送​信​す​る
			 */
			submit: string
		}
		contactInfo: {
			/**
			 * 連​絡​先
			 */
			title: string
		}
		/**
		 * G​i​t​H​u​b​連​携​が​無​効​の​た​め​、​フ​ォ​ー​ム​か​ら​の​送​信​は​で​き​ま​せ​ん​。​X​ ​(​T​w​i​t​t​e​r​)​ ​ま​た​は​G​i​t​H​u​b​か​ら​直​接​ご​連​絡​く​だ​さ​い​。
		 */
		githubDisabled: string
		success: {
			/**
			 * 送​信​完​了
			 */
			title: string
			/**
			 * G​i​t​H​u​b​で​I​s​s​u​e​を​確​認​す​る
			 */
			viewIssue: string
		}
		/**
		 * 送​信​に​失​敗​し​ま​し​た​。​時​間​を​お​い​て​再​度​お​試​し​く​だ​さ​い​。
		 */
		error: string
	}
	language: {
		/**
		 * 言​語
		 */
		title: string
		/**
		 * 日​本​語
		 */
		ja: string
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * 한​국​어
		 */
		ko: string
	}
	theme: {
		/**
		 * テ​ー​マ
		 */
		title: string
		/**
		 * ラ​イ​ト
		 */
		light: string
		/**
		 * ダ​ー​ク
		 */
		dark: string
		/**
		 * シ​ス​テ​ム​設​定​に​従​う
		 */
		system: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * 読み込み中...
		 */
		loading: () => LocalizedString
		/**
		 * 保存
		 */
		save: () => LocalizedString
		/**
		 * キャンセル
		 */
		cancel: () => LocalizedString
		/**
		 * 削除
		 */
		'delete': () => LocalizedString
		/**
		 * 編集
		 */
		edit: () => LocalizedString
		/**
		 * 追加
		 */
		add: () => LocalizedString
		/**
		 * 確認
		 */
		confirm: () => LocalizedString
		/**
		 * リセット
		 */
		reset: () => LocalizedString
		/**
		 * 更新
		 */
		update: () => LocalizedString
		/**
		 * 閉じる
		 */
		close: () => LocalizedString
		/**
		 * エラーが発生しました
		 */
		error: () => LocalizedString
		/**
		 * 不明なエラーが発生しました
		 */
		unknownError: () => LocalizedString
		/**
		 * 成功しました
		 */
		success: () => LocalizedString
		/**
		 * データの取得に失敗しました
		 */
		dataFetchError: () => LocalizedString
		/**
		 * 年
		 */
		year: () => LocalizedString
		/**
		 * 月
		 */
		month: () => LocalizedString
		/**
		 * データがありません
		 */
		noData: () => LocalizedString
		/**
		 * 必須
		 */
		required: () => LocalizedString
		screenCapture: {
			/**
			 * テンプレート読み込み失敗
			 */
			templateLoadError: () => LocalizedString
			/**
			 * 画面共有の開始に失敗しました
			 */
			startError: () => LocalizedString
		}
	}
	nav: {
		/**
		 * ダッシュボード
		 */
		dashboard: () => LocalizedString
		/**
		 * デッキ管理
		 */
		decks: () => LocalizedString
		/**
		 * 統計
		 */
		statistics: () => LocalizedString
		/**
		 * プロフィール
		 */
		profile: () => LocalizedString
		/**
		 * 管理者画面
		 */
		admin: () => LocalizedString
		/**
		 * フィードバック
		 */
		feedback: () => LocalizedString
		/**
		 * ログアウト
		 */
		logout: () => LocalizedString
	}
	auth: {
		/**
		 * 認証状態を確認中...
		 */
		checkingStatus: () => LocalizedString
		login: {
			/**
			 * ログイン
			 */
			title: () => LocalizedString
			/**
			 * メールアドレス
			 */
			email: () => LocalizedString
			/**
			 * パスワード
			 */
			password: () => LocalizedString
			/**
			 * ログイン
			 */
			submit: () => LocalizedString
			/**
			 * パスワードを忘れた場合
			 */
			forgotPassword: () => LocalizedString
			/**
			 * アカウントをお持ちでない方は
			 */
			noAccount: () => LocalizedString
			/**
			 * 新規登録
			 */
			register: () => LocalizedString
			/**
			 * ログインすることで
			 */
			termsAgreement: () => LocalizedString
			/**
			 * 利用規約
			 */
			termsLink: () => LocalizedString
			/**
			 * に同意したものとみなされます
			 */
			termsAgreementEnd: () => LocalizedString
			/**
			 * 利用規約
			 */
			termsTitle: () => LocalizedString
			/**
			 * メールアドレスまたはパスワードが正しくありません
			 */
			error: () => LocalizedString
			/**
			 * ログインに成功しました
			 */
			successMessage: () => LocalizedString
			/**
			 * または
			 */
			orDivider: () => LocalizedString
			/**
			 * Googleでログイン
			 */
			oauthGoogle: () => LocalizedString
			/**
			 * Discordでログイン
			 */
			oauthDiscord: () => LocalizedString
			features: {
				/**
				 * 詳細な統計分析
				 */
				statistics: () => LocalizedString
				/**
				 * デッキ管理・相性分析
				 */
				deckManagement: () => LocalizedString
				/**
				 * OBS配信連携
				 */
				obsIntegration: () => LocalizedString
			}
		}
		register: {
			/**
			 * 新規登録
			 */
			title: () => LocalizedString
			/**
			 * Create Your Account
			 */
			subtitle: () => LocalizedString
			/**
			 * ユーザー名
			 */
			username: () => LocalizedString
			/**
			 * メールアドレス
			 */
			email: () => LocalizedString
			/**
			 * パスワード
			 */
			password: () => LocalizedString
			/**
			 * パスワード（確認）
			 */
			confirmPassword: () => LocalizedString
			/**
			 * 新規登録
			 */
			submit: () => LocalizedString
			/**
			 * 既にアカウントをお持ちの方は
			 */
			hasAccount: () => LocalizedString
			/**
			 * ログイン
			 */
			login: () => LocalizedString
			/**
			 * 登録が完了しました！
			 */
			success: () => LocalizedString
			/**
			 * 確認メールを送信しました。メールを確認してアカウントを有効化してください。
			 */
			successWithConfirmation: () => LocalizedString
		}
		forgotPassword: {
			/**
			 * パスワードリセット
			 */
			title: () => LocalizedString
			/**
			 * Enter your email to reset your password.
			 */
			subtitle: () => LocalizedString
			/**
			 * 登録済みのメールアドレスを入力してください。パスワードリセット用のリンクをお送りします。
			 */
			description: () => LocalizedString
			/**
			 * メールアドレス
			 */
			email: () => LocalizedString
			/**
			 * 再設定メールを送信
			 */
			submit: () => LocalizedString
			/**
			 * パスワード再設定の案内をメールで送信しました。
			 */
			success: () => LocalizedString
			/**
			 * パスワードリセットメールの送信に失敗しました
			 */
			error: () => LocalizedString
			/**
			 * ログインページに戻る
			 */
			backToLogin: () => LocalizedString
		}
		resetPassword: {
			/**
			 * 新しいパスワードを設定
			 */
			title: () => LocalizedString
			/**
			 * Enter your new password.
			 */
			subtitle: () => LocalizedString
			/**
			 * 新しいパスワード
			 */
			newPassword: () => LocalizedString
			/**
			 * パスワードの確認
			 */
			confirmPassword: () => LocalizedString
			/**
			 * パスワードをリセット
			 */
			submit: () => LocalizedString
			/**
			 * パスワードが正常にリセットされました。
			 */
			success: () => LocalizedString
			/**
			 * パスワードのリセットに失敗しました
			 */
			error: () => LocalizedString
			/**
			 * 認証情報を確認中...
			 */
			checkingSession: () => LocalizedString
			/**
			 * セッションの取得に失敗しました
			 */
			sessionError: () => LocalizedString
			/**
			 * パスワードリセットリンクが無効または期限切れです
			 */
			invalidLink: () => LocalizedString
			/**
			 * ログインページに戻る
			 */
			backToLogin: () => LocalizedString
		}
		streamerMode: {
			/**
			 * 配信者モード
			 */
			label: () => LocalizedString
			/**
			 * 入力内容を非表示にし、再ログイン時にメールアドレスを保持します
			 */
			hint: () => LocalizedString
		}
	}
	dashboard: {
		/**
		 * ダッシュボード
		 */
		title: () => LocalizedString
		/**
		 * 最近の対戦
		 */
		recentDuels: () => LocalizedString
		/**
		 * 今月の成績
		 */
		quickStats: () => LocalizedString
		/**
		 * まだ対戦記録がありません
		 */
		noDuels: () => LocalizedString
		/**
		 * 最初の対戦を記録しましょう
		 */
		recordFirst: () => LocalizedString
		streak: {
			/**
			 * {count}連勝中
			 */
			winning: (arg: { count: number }) => LocalizedString
			/**
			 * {count}連敗中
			 */
			losing: (arg: { count: number }) => LocalizedString
			/**
			 * 連勝/連敗なし
			 */
			none: () => LocalizedString
		}
		emptyState: {
			/**
			 * 最初の対戦を記録しましょう
			 */
			title: () => LocalizedString
			/**
			 * 対戦結果を記録して、あなたの成長を追跡しましょう
			 */
			description: () => LocalizedString
			/**
			 * 対戦を記録
			 */
			addButton: () => LocalizedString
		}
		streamer: {
			/**
			 * 配信用ポップアップウィンドウ
			 */
			popupWindow: () => LocalizedString
			/**
			 * 推奨
			 */
			recommended: () => LocalizedString
			/**
			 * OBSブラウザソース
			 */
			obsBrowserSource: () => LocalizedString
			/**
			 * 廃止予定
			 */
			deprecated: () => LocalizedString
			/**
			 * この機能は将来廃止予定です。新しい「配信用ポップアップウィンドウ」の使用をお勧めします。
			 */
			deprecationWarning: () => LocalizedString
			/**
			 * OBSのブラウザソースで統計情報をリアルタイム表示できます。
			 */
			obsDescription: () => LocalizedString
			/**
			 * OBS URLを取得
			 */
			getObsUrl: () => LocalizedString
			/**
			 * 勝率
			 */
			winRate: () => LocalizedString
			/**
			 * 先攻勝率
			 */
			firstWinRate: () => LocalizedString
			/**
			 * 後攻勝率
			 */
			secondWinRate: () => LocalizedString
			/**
			 * コイン勝率
			 */
			coinWinRate: () => LocalizedString
			/**
			 * 先攻率
			 */
			firstRate: () => LocalizedString
		}
		duelEntry: {
			/**
			 * 対戦入力
			 */
			title: () => LocalizedString
			/**
			 * クイック入力
			 */
			quickEntry: () => LocalizedString
			/**
			 * 新規追加時の初期値
			 */
			defaultSettings: () => LocalizedString
			/**
			 * 先攻/後攻の初期値（コイン表時の基準）
			 */
			defaultTurnTooltip: () => LocalizedString
		}
		history: {
			/**
			 * 対戦履歴
			 */
			title: () => LocalizedString
			/**
			 * この期間の対戦記録はありません
			 */
			noRecords: () => LocalizedString
			/**
			 * この対戦記録を削除してもよろしいですか？
			 */
			deleteConfirm: () => LocalizedString
		}
	}
	decks: {
		/**
		 * デッキ管理
		 */
		title: () => LocalizedString
		/**
		 * 自分のデッキ
		 */
		myDecks: () => LocalizedString
		/**
		 * 相手のデッキ
		 */
		opponentDecks: () => LocalizedString
		/**
		 * 追加
		 */
		addDeck: () => LocalizedString
		/**
		 * 自分のデッキを追加
		 */
		addMyDeck: () => LocalizedString
		/**
		 * 相手のデッキを追加
		 */
		addOpponentDeck: () => LocalizedString
		/**
		 * デッキ名
		 */
		deckName: () => LocalizedString
		/**
		 * 例: 烙印、エルド、白き森
		 */
		deckNamePlaceholder: () => LocalizedString
		/**
		 * デッキが登録されていません
		 */
		noDeck: () => LocalizedString
		/**
		 * 「追加」ボタンからデッキを登録しましょう
		 */
		noDeckHint: () => LocalizedString
		/**
		 * 相手のデッキが登録されていません
		 */
		noOpponentDeck: () => LocalizedString
		/**
		 * 「追加」ボタンから相手のデッキを登録しましょう
		 */
		noOpponentDeckHint: () => LocalizedString
		/**
		 * 登録日
		 */
		registeredDate: () => LocalizedString
		/**
		 * デッキを編集
		 */
		editDeck: () => LocalizedString
		/**
		 * デッキを削除
		 */
		deleteDeck: () => LocalizedString
		/**
		 * このデッキを削除してもよろしいですか？
		 */
		deleteConfirm: () => LocalizedString
		/**
		 * 同じ名前の自分のデッキが既に存在します
		 */
		duplicateMyDeck: () => LocalizedString
		/**
		 * 同じ名前の相手のデッキが既に存在します
		 */
		duplicateOpponentDeck: () => LocalizedString
		/**
		 * デッキを登録しました
		 */
		saveSuccess: () => LocalizedString
		/**
		 * デッキを更新しました
		 */
		updateSuccess: () => LocalizedString
		/**
		 * デッキを削除しました
		 */
		deleteSuccess: () => LocalizedString
		archive: {
			/**
			 * 月次リセット機能
			 */
			title: () => LocalizedString
			/**
			 * 新弾リリース時など、全デッキを一括アーカイブできます。アーカイブしても過去の対戦記録は保持されます。
			 */
			description: () => LocalizedString
			/**
			 * 全デッキをアーカイブ
			 */
			button: () => LocalizedString
			/**
			 * 全てのデッキをアーカイブしますか？
			 */
			confirm: () => LocalizedString
			/**
			 * {count}件のデッキをアーカイブしますか？
	
		アーカイブしても過去の対戦記録は保持されます。
			 */
			confirmWithCount: (arg: { count: number }) => LocalizedString
			/**
			 * 全デッキをアーカイブしました
			 */
			success: () => LocalizedString
			/**
			 * アーカイブするデッキがありません
			 */
			noDecks: () => LocalizedString
			/**
			 * アーカイブに失敗しました
			 */
			failed: () => LocalizedString
		}
		/**
		 * アーカイブ済み
		 */
		archived: () => LocalizedString
		/**
		 * アーカイブを表示
		 */
		showArchived: () => LocalizedString
		/**
		 * アーカイブを非表示
		 */
		hideArchived: () => LocalizedString
	}
	duels: {
		/**
		 * 対戦記録
		 */
		title: () => LocalizedString
		/**
		 * 対戦を記録
		 */
		addDuel: () => LocalizedString
		/**
		 * 対戦を編集
		 */
		editDuel: () => LocalizedString
		/**
		 * 対戦を削除
		 */
		deleteDuel: () => LocalizedString
		/**
		 * この対戦記録を削除してもよろしいですか？
		 */
		deleteConfirm: () => LocalizedString
		/**
		 * 使用デッキ
		 */
		myDeck: () => LocalizedString
		/**
		 * 相手デッキ
		 */
		opponentDeck: () => LocalizedString
		result: {
			/**
			 * 勝敗
			 */
			label: () => LocalizedString
			/**
			 * 勝ち
			 */
			win: () => LocalizedString
			/**
			 * 負け
			 */
			lose: () => LocalizedString
			/**
			 * 引き分け
			 */
			draw: () => LocalizedString
		}
		turnOrder: {
			/**
			 * 先攻/後攻
			 */
			label: () => LocalizedString
			/**
			 * 先攻
			 */
			first: () => LocalizedString
			/**
			 * 後攻
			 */
			second: () => LocalizedString
		}
		coinToss: {
			/**
			 * コイン
			 */
			label: () => LocalizedString
			/**
			 * 表
			 */
			win: () => LocalizedString
			/**
			 * 裏
			 */
			lose: () => LocalizedString
		}
		gameMode: {
			/**
			 * ゲームモード
			 */
			label: () => LocalizedString
			/**
			 * ランク
			 */
			rank: () => LocalizedString
			/**
			 * レート
			 */
			rate: () => LocalizedString
			/**
			 * イベント
			 */
			event: () => LocalizedString
			/**
			 * DC
			 */
			dc: () => LocalizedString
		}
		/**
		 * 備考
		 */
		memo: () => LocalizedString
		/**
		 * 対戦日時
		 */
		playedAt: () => LocalizedString
		/**
		 * レート
		 */
		rateValue: () => LocalizedString
		/**
		 * DCポイント
		 */
		dcValue: () => LocalizedString
		/**
		 * 対戦記録を保存しました
		 */
		saveSuccess: () => LocalizedString
		/**
		 * 対戦記録を削除しました
		 */
		deleteSuccess: () => LocalizedString
		form: {
			/**
			 * 新規対戦記録
			 */
			newTitle: () => LocalizedString
			/**
			 * 対戦記録を編集
			 */
			editTitle: () => LocalizedString
			/**
			 * デッキを選択または入力
			 */
			selectOrInputDeck: () => LocalizedString
			/**
			 * 新しいデッキ名を入力できます（登録時に自動追加）
			 */
			newDeckHint: () => LocalizedString
			/**
			 * メモやコメントを入力
			 */
			memoPlaceholder: () => LocalizedString
			/**
			 * 登録
			 */
			register: () => LocalizedString
			/**
			 * 対戦記録を自動登録しました
			 */
			autoRegisterSuccess: () => LocalizedString
			/**
			 * 自動登録に失敗しました
			 */
			autoRegisterFailed: () => LocalizedString
			/**
			 * 自動登録: 使用デッキが設定されていません
			 */
			autoRegisterNoDeck: () => LocalizedString
			/**
			 * デッキの登録に失敗しました
			 */
			deckResolveFailed: () => LocalizedString
			/**
			 * 次の対戦を待機中...
			 */
			waitingNext: () => LocalizedString
			steps: {
				/**
				 * デッキ
				 */
				decks: () => LocalizedString
				/**
				 * 対戦
				 */
				battle: () => LocalizedString
				/**
				 * 詳細
				 */
				details: () => LocalizedString
			}
			/**
			 * 次へ
			 */
			next: () => LocalizedString
			/**
			 * 戻る
			 */
			prev: () => LocalizedString
		}
		table: {
			/**
			 * No.
			 */
			noColumn: () => LocalizedString
			/**
			 * ランク/レート
			 */
			rankOrRate: () => LocalizedString
			/**
			 * アクション
			 */
			actions: () => LocalizedString
			/**
			 * 対戦記録がありません
			 */
			noRecords: () => LocalizedString
			/**
			 * 「対戦記録を追加」ボタンから記録を開始しましょう
			 */
			noRecordsHint: () => LocalizedString
			/**
			 * 不明
			 */
			unknown: () => LocalizedString
		}
		screenAnalysis: {
			/**
			 * 画面解析
			 */
			title: () => LocalizedString
			/**
			 * ※テスト機能
			 */
			testFeature: () => LocalizedString
			/**
			 * テンプレート
			 */
			template: () => LocalizedString
			/**
			 * ML
			 */
			ml: () => LocalizedString
			/**
			 * 自動登録
			 */
			autoRegister: () => LocalizedString
			/**
			 * ON
			 */
			on: () => LocalizedString
			/**
			 * OFF
			 */
			off: () => LocalizedString
			/**
			 * 開始
			 */
			start: () => LocalizedString
			/**
			 * 停止
			 */
			stop: () => LocalizedString
			/**
			 * 解析中
			 */
			running: () => LocalizedString
			/**
			 * 停止中
			 */
			stopped: () => LocalizedString
			/**
			 * 選択権: 検出
			 */
			turnChoiceDetected: () => LocalizedString
			/**
			 * 選択権: 未検出
			 */
			turnChoiceNotDetected: () => LocalizedString
			/**
			 * 勝敗
			 */
			resultLabel: () => LocalizedString
			/**
			 * 未検出
			 */
			notDetected: () => LocalizedString
			/**
			 * 登録済
			 */
			registered: () => LocalizedString
			/**
			 * 登録可
			 */
			canRegister: () => LocalizedString
			/**
			 * 後攻に切替
			 */
			switchToSecond: () => LocalizedString
			/**
			 * マスターデュエルのウィンドウを選択して、画面を自動解析します。勝敗結果を検出すると自動で対戦記録を登録できます。
			 */
			description: () => LocalizedString
			/**
			 * テンプレートマッチング
			 */
			templateMode: () => LocalizedString
			/**
			 * 機械学習(TF.js)
			 */
			mlMode: () => LocalizedString
			/**
			 * モードで解析します。
			 */
			modeDescription: () => LocalizedString
			/**
			 * テンプレ未設定
			 */
			missingTemplate: () => LocalizedString
			/**
			 * 学習データ保存先フォルダを設定しました
			 */
			trainingFolderSet: () => LocalizedString
			/**
			 * フォルダの選択がキャンセルされました
			 */
			trainingFolderCancelled: () => LocalizedString
			/**
			 * 学習データを保存しました
			 */
			trainingDataSaved: () => LocalizedString
		}
	}
	statistics: {
		/**
		 * 統計情報
		 */
		title: () => LocalizedString
		filter: {
			/**
			 * 統計フィルター
			 */
			title: () => LocalizedString
			/**
			 * 期間
			 */
			period: () => LocalizedString
			/**
			 * 月別
			 */
			periodMonthly: () => LocalizedString
			/**
			 * 直近
			 */
			periodRecent: () => LocalizedString
			/**
			 * 全期間
			 */
			periodAll: () => LocalizedString
			/**
			 * 範囲指定
			 */
			periodRange: () => LocalizedString
			/**
			 * 直近{count}件
			 */
			recentCount: (arg: { count: unknown }) => LocalizedString
			/**
			 * 開始（試合目）
			 */
			rangeStart: () => LocalizedString
			/**
			 * 終了（試合目）
			 */
			rangeEnd: () => LocalizedString
			/**
			 * 自分のデッキ
			 */
			myDeck: () => LocalizedString
			/**
			 * 全てのデッキ
			 */
			allDecks: () => LocalizedString
			/**
			 * ゲームモード
			 */
			gameMode: () => LocalizedString
			/**
			 * 全モード
			 */
			allModes: () => LocalizedString
		}
		overview: {
			/**
			 * 総合成績
			 */
			title: () => LocalizedString
			/**
			 * 総対戦数
			 */
			totalMatches: () => LocalizedString
			/**
			 * 勝利
			 */
			wins: () => LocalizedString
			/**
			 * 敗北
			 */
			losses: () => LocalizedString
			/**
			 * 引き分け
			 */
			draws: () => LocalizedString
			/**
			 * 勝率
			 */
			winRate: () => LocalizedString
		}
		turnOrder: {
			/**
			 * 先攻/後攻別成績
			 */
			title: () => LocalizedString
			/**
			 * 先攻
			 */
			first: () => LocalizedString
			/**
			 * 後攻
			 */
			second: () => LocalizedString
			/**
			 * 勝率
			 */
			winRate: () => LocalizedString
		}
		coinToss: {
			/**
			 * コイントス別成績
			 */
			title: () => LocalizedString
			/**
			 * 勝ち
			 */
			win: () => LocalizedString
			/**
			 * 負け
			 */
			lose: () => LocalizedString
		}
		matchup: {
			/**
			 * デッキ相性表
			 */
			title: () => LocalizedString
			/**
			 * 使用デッキ
			 */
			myDeck: () => LocalizedString
			/**
			 * 相手デッキ
			 */
			opponent: () => LocalizedString
			/**
			 * 対戦数
			 */
			matches: () => LocalizedString
			/**
			 * 勝率
			 */
			winRate: () => LocalizedString
			/**
			 * 先攻勝率
			 */
			firstWinRate: () => LocalizedString
			/**
			 * 後攻勝率
			 */
			secondWinRate: () => LocalizedString
			/**
			 * 相性データがありません
			 */
			noData: () => LocalizedString
		}
		distribution: {
			/**
			 * デッキ分布
			 */
			title: () => LocalizedString
			/**
			 * 月間デッキ分布
			 */
			monthlyTitle: () => LocalizedString
			/**
			 * デッキ名
			 */
			deckName: () => LocalizedString
			/**
			 * 対戦数
			 */
			count: () => LocalizedString
			/**
			 * 割合
			 */
			percentage: () => LocalizedString
		}
		duelList: {
			/**
			 * 月間対戦一覧
			 */
			title: () => LocalizedString
			/**
			 * 全 {count} 件
			 */
			totalCount: (arg: { count: number }) => LocalizedString
		}
		myDeckWinRates: {
			/**
			 * 自分のデッキ勝率
			 */
			title: () => LocalizedString
		}
		rateChart: {
			/**
			 * レート推移
			 */
			title: () => LocalizedString
		}
		dcChart: {
			/**
			 * DC推移
			 */
			title: () => LocalizedString
		}
		/**
		 * データがありません
		 */
		noData: () => LocalizedString
		/**
		 * 対戦を記録すると統計が表示されます
		 */
		noDataHint: () => LocalizedString
	}
	profile: {
		/**
		 * プロフィール編集
		 */
		title: () => LocalizedString
		/**
		 * ユーザー名
		 */
		username: () => LocalizedString
		/**
		 * メールアドレス
		 */
		email: () => LocalizedString
		/**
		 * 現在のパスワード
		 */
		currentPassword: () => LocalizedString
		/**
		 * 新しいパスワード
		 */
		newPassword: () => LocalizedString
		/**
		 * 変更する場合のみ入力（8文字以上、72文字以下）
		 */
		newPasswordHint: () => LocalizedString
		/**
		 * 新しいパスワードの確認
		 */
		confirmPassword: () => LocalizedString
		/**
		 * プロフィールを更新しました
		 */
		saveSuccess: () => LocalizedString
		streamerMode: {
			/**
			 * 配信者モード
			 */
			title: () => LocalizedString
			/**
			 * 有効にすると、アプリ内のメールアドレスが自動的にマスクされます。配信や録画時のプライバシー保護に便利です。
			 */
			description: () => LocalizedString
			/**
			 * 配信者モードを有効にする
			 */
			enable: () => LocalizedString
			/**
			 * 配信者モードが有効なため、メールアドレスはマスクされています
			 */
			emailMaskedHint: () => LocalizedString
		}
		experimental: {
			/**
			 * 実験的機能
			 */
			title: () => LocalizedString
			/**
			 * テスト
			 */
			badge: () => LocalizedString
			screenAnalysis: {
				/**
				 * 画面解析機能を有効にすると、対戦記録作成時に画面キャプチャによる自動入力機能が使用できます。この機能は開発中のため、誤判定が発生する可能性があります。
				 */
				description: () => LocalizedString
				/**
				 * 画面解析機能を有効にする
				 */
				enable: () => LocalizedString
			}
		}
		accountDeletion: {
			/**
			 * アカウント削除
			 */
			title: () => LocalizedString
			/**
			 * この操作は元に戻せません。アカウントを削除すると、すべてのデッキと対戦履歴が完全に削除されます。
			 */
			warning: () => LocalizedString
			/**
			 * アカウントを削除する
			 */
			button: () => LocalizedString
			/**
			 * 本当にアカウントを削除しますか？この操作は取り消せません。
			 */
			confirm: () => LocalizedString
			/**
			 * 確認のため「削除」と入力してください
			 */
			confirmInput: () => LocalizedString
		}
		dataManagement: {
			/**
			 * データ管理
			 */
			title: () => LocalizedString
			/**
			 * 全データをCSVファイルとしてエクスポート（バックアップ）したり、インポート（復元）したりできます。
			 */
			description: () => LocalizedString
			/**
			 * エクスポート
			 */
			'export': () => LocalizedString
			/**
			 * インポート
			 */
			'import': () => LocalizedString
			/**
			 * データをエクスポートしました
			 */
			exportSuccess: () => LocalizedString
			/**
			 * データをインポートしました
			 */
			importSuccess: () => LocalizedString
			/**
			 * インポートすると既存のデータが上書きされます。続行しますか？
			 */
			importConfirm: () => LocalizedString
		}
	}
	obs: {
		/**
		 * OBSオーバーレイ
		 */
		title: () => LocalizedString
		/**
		 * OBS Studioなどの配信ソフトで使用できるオーバーレイURLを生成します。ブラウザソースとして追加してください。
		 */
		description: () => LocalizedString
		/**
		 * URLをコピー
		 */
		copyUrl: () => LocalizedString
		/**
		 * URLをコピーしました
		 */
		copySuccess: () => LocalizedString
		/**
		 * プレビュー
		 */
		preview: () => LocalizedString
		/**
		 * トークンを再生成
		 */
		regenerateToken: () => LocalizedString
		/**
		 * トークンを再生成すると、現在のURLは使用できなくなります。続行しますか？
		 */
		regenerateConfirm: () => LocalizedString
		/**
		 * URLにトークンが含まれていません
		 */
		noToken: () => LocalizedString
		settings: {
			/**
			 * 表示設定
			 */
			title: () => LocalizedString
			/**
			 * 表示期間
			 */
			period: () => LocalizedString
			/**
			 * 勝率を表示
			 */
			showWinRate: () => LocalizedString
			/**
			 * 戦績を表示
			 */
			showRecord: () => LocalizedString
			/**
			 * デッキ名を表示
			 */
			showDeck: () => LocalizedString
			/**
			 * ランクを表示
			 */
			showRank: () => LocalizedString
			/**
			 * テーマ
			 */
			theme: () => LocalizedString
			/**
			 * ライト
			 */
			themeLight: () => LocalizedString
			/**
			 * ダーク
			 */
			themeDark: () => LocalizedString
			/**
			 * 透過
			 */
			themeTransparent: () => LocalizedString
		}
		ranks: {
			/**
			 * ビギナー
			 */
			beginner: () => LocalizedString
			/**
			 * ブロンズ
			 */
			bronze: () => LocalizedString
			/**
			 * シルバー
			 */
			silver: () => LocalizedString
			/**
			 * ゴールド
			 */
			gold: () => LocalizedString
			/**
			 * プラチナ
			 */
			platinum: () => LocalizedString
			/**
			 * ダイヤ
			 */
			diamond: () => LocalizedString
			/**
			 * マスター
			 */
			master: () => LocalizedString
			/**
			 * 不明
			 */
			unknown: () => LocalizedString
		}
		streamerPopup: {
			/**
			 * 配信用ポップアップ設定
			 */
			title: () => LocalizedString
			/**
			 * ゲームモード
			 */
			gameMode: () => LocalizedString
			/**
			 * レイアウト
			 */
			layout: () => LocalizedString
			/**
			 * 自動更新間隔
			 */
			refreshInterval: () => LocalizedString
			/**
			 * 表示項目
			 */
			displayItems: () => LocalizedString
			/**
			 * {count}個選択中
			 */
			displayItemsCount: (arg: { count: number }) => LocalizedString
			/**
			 * ポップアップを開く
			 */
			openPopup: () => LocalizedString
			gameModes: {
				/**
				 * ランクマッチ
				 */
				rank: () => LocalizedString
				/**
				 * レートマッチ
				 */
				rate: () => LocalizedString
				/**
				 * イベント
				 */
				event: () => LocalizedString
				/**
				 * デュエリストカップ
				 */
				dc: () => LocalizedString
			}
			layouts: {
				/**
				 * グリッド（自動調整）
				 */
				grid: () => LocalizedString
				/**
				 * 横並び
				 */
				horizontal: () => LocalizedString
				/**
				 * 縦並び
				 */
				vertical: () => LocalizedString
			}
			intervals: {
				/**
				 * 10秒
				 */
				sec10: () => LocalizedString
				/**
				 * 30秒
				 */
				sec30: () => LocalizedString
				/**
				 * 1分
				 */
				min1: () => LocalizedString
			}
			/**
			 * 統計期間
			 */
			statsPeriod: () => LocalizedString
			statsPeriods: {
				/**
				 * 当月
				 */
				monthly: () => LocalizedString
				/**
				 * 配信開始から
				 */
				session: () => LocalizedString
			}
			items: {
				/**
				 * 使用デッキ
				 */
				currentDeck: () => LocalizedString
				/**
				 * ランク/レート/DC（ゲームモードに連動）
				 */
				gameModeValue: () => LocalizedString
				/**
				 * 総試合数
				 */
				totalDuels: () => LocalizedString
				/**
				 * 勝率
				 */
				winRate: () => LocalizedString
				/**
				 * 先攻勝率
				 */
				firstTurnWinRate: () => LocalizedString
				/**
				 * 後攻勝率
				 */
				secondTurnWinRate: () => LocalizedString
				/**
				 * コイン勝率
				 */
				coinWinRate: () => LocalizedString
				/**
				 * 先攻率
				 */
				goFirstRate: () => LocalizedString
				/**
				 * ランク
				 */
				rank: () => LocalizedString
				/**
				 * レート
				 */
				rate: () => LocalizedString
				/**
				 * DC
				 */
				dc: () => LocalizedString
				/**
				 * 未設定
				 */
				notSet: () => LocalizedString
			}
			/**
			 * ログインが必要です
			 */
			loginRequired: () => LocalizedString
			/**
			 * ログイン状態でこのページを開いてください
			 */
			loginRequiredDetail: () => LocalizedString
			chromaKey: {
				/**
				 * クロマキー背景
				 */
				title: () => LocalizedString
				/**
				 * ウィンドウキャプチャ時にOBSのクロマキーフィルターで背景を透過できます。
				 */
				description: () => LocalizedString
				/**
				 * 通常
				 */
				none: () => LocalizedString
				/**
				 * グリーン
				 */
				green: () => LocalizedString
				/**
				 * ブルー
				 */
				blue: () => LocalizedString
			}
		}
		configPanel: {
			/**
			 * OBS連携設定
			 */
			title: () => LocalizedString
			/**
			 * OBSのブラウザソースで統計情報をリアルタイムでオーバーレイ表示できます。表示する項目と集計期間をカスタマイズできます。
			 */
			description: () => LocalizedString
			/**
			 * 集計期間
			 */
			periodType: () => LocalizedString
			/**
			 * 月間
			 */
			periodMonthly: () => LocalizedString
			/**
			 * 直近N戦
			 */
			periodRecent: () => LocalizedString
			/**
			 * 累計
			 */
			periodFromStart: () => LocalizedString
			/**
			 * 年
			 */
			year: () => LocalizedString
			/**
			 * 月
			 */
			month: () => LocalizedString
			/**
			 * 表示する試合数
			 */
			matchCount: () => LocalizedString
			/**
			 * ゲームモード（任意）
			 */
			gameModeOptional: () => LocalizedString
			/**
			 * 表示する項目を選択（ドラッグで並び替え可能）
			 */
			displayItemsTitle: () => LocalizedString
			/**
			 * 更新間隔（ミリ秒）
			 */
			refreshIntervalMs: () => LocalizedString
			/**
			 * OBSでの設定方法：
			 */
			obsSetupGuide: () => LocalizedString
			/**
			 * OBSで「ソース」→「+」→「ブラウザ」を選択
			 */
			obsStep1: () => LocalizedString
			/**
			 * 以下のURLをコピーして「URL」欄に貼り付け
			 */
			obsStep2: () => LocalizedString
			/**
			 * カスタムCSSで背景を透過:
			 */
			obsStep4: () => LocalizedString
			/**
			 * OBS用URL
			 */
			obsUrl: () => LocalizedString
			/**
			 * ※ このURLには認証トークンが含まれています。他人と共有しないでください。
			 */
			urlWarning: () => LocalizedString
			/**
			 * 幅: 800px、高さ: 600px を推奨
			 */
			recommendedSizeGrid: () => LocalizedString
			/**
			 * 幅: 1920px、高さ: 200px を推奨（下部に配置）
			 */
			recommendedSizeHorizontal: () => LocalizedString
			/**
			 * 幅: 250px、高さ: 1080px を推奨（右端に配置）
			 */
			recommendedSizeVertical: () => LocalizedString
			/**
			 * OBS用トークンの取得に失敗しました。再ログインしてください
			 */
			tokenFetchError: () => LocalizedString
			/**
			 * URLをコピーしました
			 */
			urlCopySuccess: () => LocalizedString
			/**
			 * URLのコピーに失敗しました
			 */
			urlCopyError: () => LocalizedString
			items: {
				/**
				 * 勝率
				 */
				winRate: () => LocalizedString
				/**
				 * 総試合数
				 */
				record: () => LocalizedString
				/**
				 * 使用デッキ
				 */
				deck: () => LocalizedString
				/**
				 * 現在のランク
				 */
				rank: () => LocalizedString
				/**
				 * 現在のレート
				 */
				rate: () => LocalizedString
				/**
				 * 現在のDC
				 */
				dc: () => LocalizedString
				/**
				 * 先攻勝率
				 */
				firstTurnWinRate: () => LocalizedString
				/**
				 * 後攻勝率
				 */
				secondTurnWinRate: () => LocalizedString
				/**
				 * コイン勝率
				 */
				coinTossWinRate: () => LocalizedString
				/**
				 * 先攻率
				 */
				goFirstRate: () => LocalizedString
			}
		}
	}
	shared: {
		/**
		 * 統計を共有
		 */
		title: () => LocalizedString
		/**
		 * 統計情報を公開URLで共有できます。
		 */
		description: () => LocalizedString
		/**
		 * 共有リンクを作成
		 */
		createLink: () => LocalizedString
		/**
		 * リンクをコピー
		 */
		copyLink: () => LocalizedString
		/**
		 * リンクをコピーしました
		 */
		copySuccess: () => LocalizedString
		/**
		 * 共有を停止
		 */
		deleteLink: () => LocalizedString
		/**
		 * 共有を停止すると、このURLは使用できなくなります。続行しますか？
		 */
		deleteConfirm: () => LocalizedString
		/**
		 * 公開統計
		 */
		publicStats: () => LocalizedString
		/**
		 * 閲覧数
		 */
		viewerCount: () => LocalizedString
		/**
		 * 共有リンクが生成されました！
		 */
		createSuccess: () => LocalizedString
		/**
		 * 共有リンクの生成に失敗しました。
		 */
		createError: () => LocalizedString
		/**
		 * 共有統計データの取得に失敗しました。
		 */
		fetchError: () => LocalizedString
		/**
		 * 共有リンクが削除されました。
		 */
		deleteSuccess: () => LocalizedString
		/**
		 * 共有リンクの削除に失敗しました。
		 */
		deleteError: () => LocalizedString
		dialog: {
			/**
			 * 共有リンクを生成
			 */
			title: () => LocalizedString
			/**
			 * 有効期限 (YYYY-MM-DD, オプション)
			 */
			expiresAt: () => LocalizedString
			/**
			 * リンクを生成
			 */
			generateButton: () => LocalizedString
			/**
			 * 有効期限の日付形式が不正です。YYYY-MM-DD 形式で入力してください。
			 */
			invalidDateFormat: () => LocalizedString
			/**
			 * 有効期限の日付が不正です。存在しない日付が入力されました。
			 */
			invalidDate: () => LocalizedString
			/**
			 * リンクのコピーに失敗しました。手動でコピーしてください。
			 */
			copyFailed: () => LocalizedString
		}
	}
	validation: {
		/**
		 * 必須項目です
		 */
		required: () => LocalizedString
		/**
		 * 有効なメールアドレスを入力してください
		 */
		email: () => LocalizedString
		/**
		 * {min}文字以上で入力してください
		 */
		minLength: (arg: { min: number }) => LocalizedString
		/**
		 * {max}文字以内で入力してください
		 */
		maxLength: (arg: { max: number }) => LocalizedString
		/**
		 * パスワードが一致しません
		 */
		passwordMatch: () => LocalizedString
		/**
		 * パスワードは8文字以上で入力してください
		 */
		passwordMinLength: () => LocalizedString
		/**
		 * パスワードは6文字以上で入力してください
		 */
		passwordMinLength6: () => LocalizedString
		/**
		 * ユーザー名は3文字以上で入力してください
		 */
		username: () => LocalizedString
		/**
		 * 形式が正しくありません
		 */
		invalidFormat: () => LocalizedString
		/**
		 * 予期せぬエラーが発生しました
		 */
		unexpectedError: () => LocalizedString
		/**
		 * 0以上の数値を入力してください
		 */
		positiveNumber: () => LocalizedString
		/**
		 * 整数を入力してください
		 */
		integer: () => LocalizedString
	}
	admin: {
		/**
		 * 管理者画面
		 */
		title: () => LocalizedString
		users: {
			/**
			 * ユーザー管理
			 */
			title: () => LocalizedString
			/**
			 * 総ユーザー数
			 */
			totalUsers: () => LocalizedString
			/**
			 * アクティブユーザー
			 */
			activeUsers: () => LocalizedString
		}
		maintenance: {
			/**
			 * メンテナンス
			 */
			title: () => LocalizedString
			/**
			 * スキャン
			 */
			scan: () => LocalizedString
			/**
			 * クリーンアップ
			 */
			cleanup: () => LocalizedString
			/**
			 * 一括削除
			 */
			bulkDelete: () => LocalizedString
			/**
			 * 実行
			 */
			execute: () => LocalizedString
			/**
			 * 警告：
			 */
			warning: () => LocalizedString
			/**
			 * この操作は取り消せません。
			 */
			cannotUndo: () => LocalizedString
			/**
			 * 続行しますか？
			 */
			confirmProceed: () => LocalizedString
			/**
			 * 完了
			 */
			success: () => LocalizedString
			/**
			 * 失敗
			 */
			failed: () => LocalizedString
			/**
			 * スキャンに失敗しました
			 */
			scanError: () => LocalizedString
			/**
			 * クリーンアップに失敗しました
			 */
			cleanupError: () => LocalizedString
			mergeDeck: {
				/**
				 * アーカイブデッキのマージ
				 */
				title: () => LocalizedString
				/**
				 * 同じ名前のアーカイブ済みデッキを現在のデッキにマージします。
				 */
				description: () => LocalizedString
				/**
				 * マージを実行
				 */
				button: () => LocalizedString
				/**
				 * マージの確認
				 */
				confirmTitle: () => LocalizedString
				/**
				 * アーカイブされたデッキを同名の現在のデッキにマージします。
				 */
				confirmMessage: () => LocalizedString
				/**
				 * デッキのマージが完了しました
				 */
				success: () => LocalizedString
				/**
				 * デッキのマージに失敗しました
				 */
				error: () => LocalizedString
			}
			orphanedDecks: {
				/**
				 * 孤立デッキのクリーンアップ
				 */
				title: () => LocalizedString
				/**
				 * 対戦記録から参照されていない相手デッキを検出・削除します。
				 */
				description: () => LocalizedString
				/**
				 * 件の孤立デッキが見つかりました
				 */
				found: () => LocalizedString
				/**
				 * 孤立デッキの削除
				 */
				confirmTitle: () => LocalizedString
				/**
				 * 件の孤立デッキを削除します。
				 */
				confirmMessage: () => LocalizedString
			}
			sharedUrls: {
				/**
				 * 共有URLのクリーンアップ
				 */
				title: () => LocalizedString
				orphaned: {
					/**
					 * 孤立した共有URL
					 */
					title: () => LocalizedString
					/**
					 * 削除されたユーザーに紐づく共有URLを検出・削除します。
					 */
					description: () => LocalizedString
					/**
					 * 件の孤立した共有URLが見つかりました
					 */
					found: () => LocalizedString
					/**
					 * 孤立URLの削除
					 */
					confirmTitle: () => LocalizedString
					/**
					 * 件の孤立した共有URLを削除します。
					 */
					confirmMessage: () => LocalizedString
				}
				expired: {
					/**
					 * 期限切れ共有URL
					 */
					title: () => LocalizedString
					/**
					 * 有効期限が切れた共有URLを検出・削除します。
					 */
					description: () => LocalizedString
					/**
					 * 件の期限切れ共有URLが見つかりました
					 */
					found: () => LocalizedString
					/**
					 * 最も古い期限切れ
					 */
					oldest: () => LocalizedString
					/**
					 * 期限切れURLの削除
					 */
					confirmTitle: () => LocalizedString
					/**
					 * 件の期限切れ共有URLを削除します。
					 */
					confirmMessage: () => LocalizedString
				}
			}
		}
		statistics: {
			/**
			 * システム統計
			 */
			title: () => LocalizedString
			/**
			 * 総ユーザー数
			 */
			totalUsers: () => LocalizedString
			/**
			 * 今月
			 */
			thisMonth: () => LocalizedString
			/**
			 * 総デッキ数
			 */
			totalDecks: () => LocalizedString
			/**
			 * アクティブ/アーカイブ
			 */
			activeArchived: () => LocalizedString
			/**
			 * 総対戦数
			 */
			totalDuels: () => LocalizedString
			/**
			 * 今月のアクティブユーザー
			 */
			activeUsersThisMonth: () => LocalizedString
			/**
			 * ゲームモード別内訳
			 */
			gameModeBreakdown: () => LocalizedString
			/**
			 * 対戦数推移
			 */
			duelsTimeline: () => LocalizedString
			/**
			 * ユーザー登録数推移
			 */
			userRegistrations: () => LocalizedString
			/**
			 * 対戦数
			 */
			duelsCount: () => LocalizedString
			/**
			 * 新規ユーザー
			 */
			newUsers: () => LocalizedString
		}
		userDetail: {
			/**
			 * 基本情報
			 */
			basicInfo: () => LocalizedString
			/**
			 * メールアドレス
			 */
			email: () => LocalizedString
			/**
			 * 登録日
			 */
			registeredAt: () => LocalizedString
			/**
			 * 最終ログイン
			 */
			lastLoginAt: () => LocalizedString
			/**
			 * テーマ
			 */
			theme: () => LocalizedString
			/**
			 * 状態変更理由
			 */
			statusReason: () => LocalizedString
			/**
			 * 利用統計
			 */
			stats: () => LocalizedString
			/**
			 * 総対戦数
			 */
			totalDuels: () => LocalizedString
			/**
			 * 今月の対戦
			 */
			thisMonthDuels: () => LocalizedString
			/**
			 * 勝率
			 */
			winRate: () => LocalizedString
			/**
			 * 勝敗
			 */
			winLoss: () => LocalizedString
			/**
			 * 自分のデッキ
			 */
			playerDecks: () => LocalizedString
			/**
			 * 相手のデッキ
			 */
			opponentDecks: () => LocalizedString
			/**
			 * 機能利用状況
			 */
			featureUsage: () => LocalizedString
			/**
			 * 配信者モード
			 */
			streamerMode: () => LocalizedString
			/**
			 * OBSオーバーレイ
			 */
			obsOverlay: () => LocalizedString
			/**
			 * 統計共有
			 */
			sharedStats: () => LocalizedString
			/**
			 * 画面分析
			 */
			screenAnalysis: () => LocalizedString
			/**
			 * 状態を変更
			 */
			changeStatus: () => LocalizedString
			/**
			 * パスワードリセット
			 */
			resetPassword: () => LocalizedString
			/**
			 * 有効
			 */
			statusActive: () => LocalizedString
			/**
			 * 停止中
			 */
			statusSuspended: () => LocalizedString
			/**
			 * 削除済み
			 */
			statusDeleted: () => LocalizedString
			/**
			 * アカウント状態の変更
			 */
			changeStatusTitle: () => LocalizedString
			/**
			 * {username} の状態を変更します。
			 */
			changeStatusDescription: (arg: { username: string }) => LocalizedString
			/**
			 * 新しい状態
			 */
			newStatus: () => LocalizedString
			/**
			 * 理由（任意）
			 */
			reason: () => LocalizedString
			/**
			 * 状態変更の理由を入力してください
			 */
			reasonPlaceholder: () => LocalizedString
			/**
			 * アカウントを停止すると、ユーザーはログインできなくなります。
			 */
			suspendedWarning: () => LocalizedString
			/**
			 * アカウントを削除扱いにすると、復旧が必要になります。
			 */
			deletedWarning: () => LocalizedString
		}
		meta: {
			/**
			 * メタ分析
			 */
			title: () => LocalizedString
			/**
			 * 期間
			 */
			period: () => LocalizedString
			/**
			 * ゲームモード
			 */
			gameMode: () => LocalizedString
			/**
			 * 最小使用回数
			 */
			minUsage: () => LocalizedString
			/**
			 * 7日間
			 */
			period7days: () => LocalizedString
			/**
			 * 14日間
			 */
			period14days: () => LocalizedString
			/**
			 * 30日間
			 */
			period30days: () => LocalizedString
			/**
			 * 60日間
			 */
			period60days: () => LocalizedString
			/**
			 * 90日間
			 */
			period90days: () => LocalizedString
			/**
			 * 人気デッキランキング
			 */
			popularDecks: () => LocalizedString
			/**
			 * デッキ使用率推移
			 */
			deckTrends: () => LocalizedString
			/**
			 * ゲームモード別統計
			 */
			gameModeStats: () => LocalizedString
			/**
			 * 総対戦数
			 */
			totalDuels: () => LocalizedString
			/**
			 * データがありません
			 */
			noData: () => LocalizedString
		}
	}
	help: {
		/**
		 * ヘルプ
		 */
		title: () => LocalizedString
		/**
		 * バグを報告
		 */
		bugReport: () => LocalizedString
		/**
		 * 機能をリクエスト
		 */
		featureRequest: () => LocalizedString
		/**
		 * お問い合わせ
		 */
		contact: () => LocalizedString
		/**
		 * Twitter/X
		 */
		twitter: () => LocalizedString
		/**
		 * バージョン
		 */
		version: () => LocalizedString
	}
	feedback: {
		/**
		 * バグ報告、機能要望、お問い合わせをお待ちしております。GitHubのIssueとして登録されます。
		 */
		intro: () => LocalizedString
		tabs: {
			/**
			 * バグ報告
			 */
			bug: () => LocalizedString
			/**
			 * 機能要望
			 */
			enhancement: () => LocalizedString
			/**
			 * お問い合わせ
			 */
			contact: () => LocalizedString
		}
		form: {
			/**
			 * タイトル
			 */
			title: () => LocalizedString
			/**
			 * 説明
			 */
			description: () => LocalizedString
		}
		bug: {
			/**
			 * バグの概要を入力
			 */
			titlePlaceholder: () => LocalizedString
			/**
			 * バグの詳細を入力してください
			 */
			descriptionPlaceholder: () => LocalizedString
			/**
			 * 再現手順
			 */
			steps: () => LocalizedString
			/**
			 * 1. ○○を開く
		2. ○○をクリック
		3. エラーが発生
			 */
			stepsPlaceholder: () => LocalizedString
			/**
			 * 期待する動作
			 */
			expected: () => LocalizedString
			/**
			 * 本来どうなるべきか
			 */
			expectedPlaceholder: () => LocalizedString
			/**
			 * 実際の動作
			 */
			actual: () => LocalizedString
			/**
			 * 実際に何が起きたか
			 */
			actualPlaceholder: () => LocalizedString
			/**
			 * バグを報告する
			 */
			submit: () => LocalizedString
		}
		enhancement: {
			/**
			 * 機能の概要を入力
			 */
			titlePlaceholder: () => LocalizedString
			/**
			 * 追加してほしい機能の詳細を入力してください
			 */
			descriptionPlaceholder: () => LocalizedString
			/**
			 * ユースケース
			 */
			useCase: () => LocalizedString
			/**
			 * どのような場面で使いたいか
			 */
			useCasePlaceholder: () => LocalizedString
			/**
			 * 機能を要望する
			 */
			submit: () => LocalizedString
		}
		contact: {
			/**
			 * 件名
			 */
			subject: () => LocalizedString
			/**
			 * お問い合わせの件名を入力
			 */
			subjectPlaceholder: () => LocalizedString
			/**
			 * メッセージ
			 */
			message: () => LocalizedString
			/**
			 * お問い合わせ内容を入力してください
			 */
			messagePlaceholder: () => LocalizedString
			/**
			 * 送信する
			 */
			submit: () => LocalizedString
		}
		contactInfo: {
			/**
			 * 連絡先
			 */
			title: () => LocalizedString
		}
		/**
		 * GitHub連携が無効のため、フォームからの送信はできません。X (Twitter) またはGitHubから直接ご連絡ください。
		 */
		githubDisabled: () => LocalizedString
		success: {
			/**
			 * 送信完了
			 */
			title: () => LocalizedString
			/**
			 * GitHubでIssueを確認する
			 */
			viewIssue: () => LocalizedString
		}
		/**
		 * 送信に失敗しました。時間をおいて再度お試しください。
		 */
		error: () => LocalizedString
	}
	language: {
		/**
		 * 言語
		 */
		title: () => LocalizedString
		/**
		 * 日本語
		 */
		ja: () => LocalizedString
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * 한국어
		 */
		ko: () => LocalizedString
	}
	theme: {
		/**
		 * テーマ
		 */
		title: () => LocalizedString
		/**
		 * ライト
		 */
		light: () => LocalizedString
		/**
		 * ダーク
		 */
		dark: () => LocalizedString
		/**
		 * システム設定に従う
		 */
		system: () => LocalizedString
	}
}

export type Formatters = {}
